# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(800, 400))
        Dialog.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBoxID = QtWidgets.QSpinBox(self.widget)
        self.spinBoxID.setMinimumSize(QtCore.QSize(0, 40))
        self.spinBoxID.setMinimum(1)
        self.spinBoxID.setMaximum(999999999)
        self.spinBoxID.setObjectName("spinBoxID")
        self.gridLayout.addWidget(self.spinBoxID, 0, 2, 1, 1)
        self.doubleSpinBoxSalary = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSalary.setMinimumSize(QtCore.QSize(0, 40))
        self.doubleSpinBoxSalary.setMaximum(1e+20)
        self.doubleSpinBoxSalary.setSingleStep(100.0)
        self.doubleSpinBoxSalary.setObjectName("doubleSpinBoxSalary")
        self.gridLayout.addWidget(self.doubleSpinBoxSalary, 6, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 2, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.widget)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 1, 2, 1, 1)
        self.lineEditCountry = QtWidgets.QLineEdit(self.widget)
        self.lineEditCountry.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEditCountry.setObjectName("lineEditCountry")
        self.gridLayout.addWidget(self.lineEditCountry, 4, 2, 1, 1)
        self.spinBoxAge = QtWidgets.QSpinBox(self.widget)
        self.spinBoxAge.setMinimumSize(QtCore.QSize(0, 40))
        self.spinBoxAge.setMinimum(-1)
        self.spinBoxAge.setMaximum(200)
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.gridLayout.addWidget(self.spinBoxAge, 5, 2, 1, 1)
        self.comboBoxSex = QtWidgets.QComboBox(self.widget)
        self.comboBoxSex.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBoxSex.setObjectName("comboBoxSex")
        self.gridLayout.addWidget(self.comboBoxSex, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.LabImage = QtWidgets.QLabel(self.widget_2)
        self.LabImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LabImage.setObjectName("LabImage")
        self.gridLayout_2.addWidget(self.LabImage, 2, 0, 4, 3)
        self.btnCancel = QtWidgets.QPushButton(self.widget_2)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/706.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_2.addWidget(self.btnCancel, 3, 3, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.widget_2)
        self.btnClear.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/103.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon1)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_2.addWidget(self.btnClear, 1, 3, 1, 1)
        self.btnOk = QtWidgets.QPushButton(self.widget_2)
        self.btnOk.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/704.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon2)
        self.btnOk.setObjectName("btnOk")
        self.gridLayout_2.addWidget(self.btnOk, 2, 3, 1, 1)
        self.btnImport = QtWidgets.QPushButton(self.widget_2)
        self.btnImport.setMinimumSize(QtCore.QSize(0, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/00.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImport.setIcon(icon3)
        self.btnImport.setObjectName("btnImport")
        self.gridLayout_2.addWidget(self.btnImport, 0, 3, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(Dialog)
        self.btnOk.clicked.connect(Dialog.accept)
        self.btnCancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ID"))
        self.label_2.setText(_translate("Dialog", "Name"))
        self.label_3.setText(_translate("Dialog", "Sex"))
        self.label_4.setText(_translate("Dialog", "Birth"))
        self.label_5.setText(_translate("Dialog", "Country"))
        self.label_6.setText(_translate("Dialog", "Age"))
        self.label_7.setText(_translate("Dialog", "Salary"))
        self.label_8.setText(_translate("Dialog", "image"))
        self.LabImage.setText(_translate("Dialog", "NULL"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.btnClear.setText(_translate("Dialog", "clear image"))
        self.btnOk.setText(_translate("Dialog", "OK"))
        self.btnImport.setText(_translate("Dialog", "import image"))
import res_rc
