# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qlistwidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QListWidget(object):
    def setupUi(self, QListWidget):
        QListWidget.setObjectName("QListWidget")
        QListWidget.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QListWidget.sizePolicy().hasHeightForWidth())
        QListWidget.setSizePolicy(sizePolicy)
        QListWidget.setMinimumSize(QtCore.QSize(800, 600))
        QListWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(QListWidget)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralWidget)
        self.toolBox.setAutoFillBackground(True)
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtWidgets.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 157, 444))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnList = QtWidgets.QToolButton(self.page1)
        self.btnList.setMinimumSize(QtCore.QSize(100, 30))
        self.btnList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnList.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/128.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnList.setIcon(icon)
        self.btnList.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnList.setAutoRaise(False)
        self.btnList.setObjectName("btnList")
        self.verticalLayout.addWidget(self.btnList)
        self.btnPlus = QtWidgets.QToolButton(self.page1)
        self.btnPlus.setMinimumSize(QtCore.QSize(100, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlus.setIcon(icon1)
        self.btnPlus.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnPlus.setObjectName("btnPlus")
        self.verticalLayout.addWidget(self.btnPlus)
        self.btnInsert = QtWidgets.QToolButton(self.page1)
        self.btnInsert.setMinimumSize(QtCore.QSize(100, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/318.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInsert.setIcon(icon2)
        self.btnInsert.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnInsert.setObjectName("btnInsert")
        self.verticalLayout.addWidget(self.btnInsert)
        self.btnDelete = QtWidgets.QToolButton(self.page1)
        self.btnDelete.setMinimumSize(QtCore.QSize(100, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon3)
        self.btnDelete.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        self.btnSelect = QtWidgets.QToolButton(self.page1)
        self.btnSelect.setMinimumSize(QtCore.QSize(100, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/124.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelect.setIcon(icon4)
        self.btnSelect.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnSelect.setAutoRaise(False)
        self.btnSelect.setArrowType(QtCore.Qt.NoArrow)
        self.btnSelect.setObjectName("btnSelect")
        self.verticalLayout.addWidget(self.btnSelect)
        self.toolBox.addItem(self.page1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.toolBox.addItem(self.page2, "")
        self.page3 = QtWidgets.QWidget()
        self.page3.setGeometry(QtCore.QRect(0, 0, 157, 444))
        self.page3.setObjectName("page3")
        self.toolBox.addItem(self.page3, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 621, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btnUnall = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.btnUnall.setMinimumSize(QtCore.QSize(100, 30))
        self.btnUnall.setObjectName("btnUnall")
        self.gridLayout.addWidget(self.btnUnall, 1, 3, 1, 1)
        self.btnAll = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.btnAll.setMinimumSize(QtCore.QSize(100, 30))
        self.btnAll.setObjectName("btnAll")
        self.gridLayout.addWidget(self.btnAll, 1, 2, 1, 1)
        self.btnInverse = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.btnInverse.setMinimumSize(QtCore.QSize(100, 30))
        self.btnInverse.setObjectName("btnInverse")
        self.gridLayout.addWidget(self.btnInverse, 1, 4, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 5)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton.setMinimumSize(QtCore.QSize(150, 30))
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tabWidget.addTab(self.tab3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        QListWidget.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(QListWidget)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menuBar.setObjectName("menuBar")
        QListWidget.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(QListWidget)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        QListWidget.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(QListWidget)
        self.statusBar.setObjectName("statusBar")
        QListWidget.setStatusBar(self.statusBar)
        self.actionlist = QtWidgets.QAction(QListWidget)
        self.actionlist.setIcon(icon)
        self.actionlist.setObjectName("actionlist")
        self.actiondelete = QtWidgets.QAction(QListWidget)
        self.actiondelete.setIcon(icon3)
        self.actiondelete.setObjectName("actiondelete")
        self.actionplus = QtWidgets.QAction(QListWidget)
        self.actionplus.setIcon(icon1)
        self.actionplus.setObjectName("actionplus")
        self.actioninsert = QtWidgets.QAction(QListWidget)
        self.actioninsert.setCheckable(False)
        self.actioninsert.setIcon(icon1)
        self.actioninsert.setObjectName("actioninsert")
        self.actionselect = QtWidgets.QAction(QListWidget)
        self.actionselect.setIcon(icon4)
        self.actionselect.setObjectName("actionselect")
        self.actionexit = QtWidgets.QAction(QListWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexit.setIcon(icon5)
        self.actionexit.setObjectName("actionexit")
        self.actionPopMenu = QtWidgets.QAction(QListWidget)
        self.actionPopMenu.setObjectName("actionPopMenu")
        self.actionselect_all = QtWidgets.QAction(QListWidget)
        self.actionselect_all.setObjectName("actionselect_all")
        self.actionunselect_all = QtWidgets.QAction(QListWidget)
        self.actionunselect_all.setObjectName("actionunselect_all")
        self.actioninverse = QtWidgets.QAction(QListWidget)
        self.actioninverse.setObjectName("actioninverse")
        self.actionclear = QtWidgets.QAction(QListWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/105.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionclear.setIcon(icon6)
        self.actionclear.setObjectName("actionclear")
        self.mainToolBar.addAction(self.actionlist)
        self.mainToolBar.addAction(self.actionplus)
        self.mainToolBar.addAction(self.actioninsert)
        self.mainToolBar.addAction(self.actiondelete)
        self.mainToolBar.addAction(self.actionselect)
        self.mainToolBar.addAction(self.actionclear)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionexit)

        self.retranslateUi(QListWidget)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QListWidget)

    def retranslateUi(self, QListWidget):
        _translate = QtCore.QCoreApplication.translate
        QListWidget.setWindowTitle(_translate("QListWidget", "QListWidget"))
        self.btnList.setText(_translate("QListWidget", "list"))
        self.btnPlus.setText(_translate("QListWidget", "plus"))
        self.btnInsert.setText(_translate("QListWidget", "insert"))
        self.btnDelete.setText(_translate("QListWidget", "delete"))
        self.btnSelect.setText(_translate("QListWidget", "select"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("QListWidget", "QListWidget"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("QListWidget", "QTreeWidget"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page3), _translate("QListWidget", "QTableWidget"))
        self.label.setText(_translate("QListWidget", "item:"))
        self.btnUnall.setText(_translate("QListWidget", "unselect all"))
        self.btnAll.setText(_translate("QListWidget", "select all"))
        self.btnInverse.setText(_translate("QListWidget", "inverse"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("QListWidget", "hello world"))
        item = self.listWidget.item(1)
        item.setText(_translate("QListWidget", "good"))
        item = self.listWidget.item(2)
        item.setText(_translate("QListWidget", "think"))
        item = self.listWidget.item(3)
        item.setText(_translate("QListWidget", "idea"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.checkBox.setText(_translate("QListWidget", "editable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("QListWidget", "QListWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("QListWidget", "QTreeWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("QListWidget", "QTableWidget"))
        self.actionlist.setText(_translate("QListWidget", "list"))
        self.actiondelete.setText(_translate("QListWidget", "delete"))
        self.actionplus.setText(_translate("QListWidget", "plus"))
        self.actioninsert.setText(_translate("QListWidget", "insert"))
        self.actionselect.setText(_translate("QListWidget", "select"))
        self.actionexit.setText(_translate("QListWidget", "exit"))
        self.actionPopMenu.setText(_translate("QListWidget", "<---select--->"))
        self.actionselect_all.setText(_translate("QListWidget", "select_all"))
        self.actionunselect_all.setText(_translate("QListWidget", "unselect_all"))
        self.actioninverse.setText(_translate("QListWidget", "inverse"))
        self.actionclear.setText(_translate("QListWidget", "clear"))
import res_rc
