# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(477, 313)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnOpenMoreFile = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenMoreFile.setObjectName("btnOpenMoreFile")
        self.gridLayout.addWidget(self.btnOpenMoreFile, 0, 1, 1, 1)
        self.btnFont = QtWidgets.QPushButton(self.groupBox)
        self.btnFont.setObjectName("btnFont")
        self.gridLayout.addWidget(self.btnFont, 2, 1, 1, 1)
        self.btnSelectDirection = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectDirection.setObjectName("btnSelectDirection")
        self.gridLayout.addWidget(self.btnSelectDirection, 1, 0, 1, 1)
        self.btnOpenFile = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.gridLayout.addWidget(self.btnOpenFile, 0, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 1, 1, 1, 1)
        self.btnColor = QtWidgets.QPushButton(self.groupBox)
        self.btnColor.setObjectName("btnColor")
        self.gridLayout.addWidget(self.btnColor, 2, 0, 1, 1)
        self.btnProgress = QtWidgets.QPushButton(self.groupBox)
        self.btnProgress.setObjectName("btnProgress")
        self.gridLayout.addWidget(self.btnProgress, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnInfo = QtWidgets.QPushButton(self.groupBox_2)
        self.btnInfo.setObjectName("btnInfo")
        self.gridLayout_2.addWidget(self.btnInfo, 0, 1, 1, 1)
        self.btnCritical = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCritical.setObjectName("btnCritical")
        self.gridLayout_2.addWidget(self.btnCritical, 1, 1, 1, 1)
        self.btnWarning = QtWidgets.QPushButton(self.groupBox_2)
        self.btnWarning.setObjectName("btnWarning")
        self.gridLayout_2.addWidget(self.btnWarning, 1, 0, 1, 1)
        self.btnQuestion = QtWidgets.QPushButton(self.groupBox_2)
        self.btnQuestion.setObjectName("btnQuestion")
        self.gridLayout_2.addWidget(self.btnQuestion, 0, 0, 1, 1)
        self.btnAbout = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAbout.setObjectName("btnAbout")
        self.gridLayout_2.addWidget(self.btnAbout, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnExit = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout_3.addWidget(self.btnExit, 0, 3, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/212.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon1)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_3.addWidget(self.btnClear, 0, 2, 1, 1)
        self.btnInputString = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInputString.setObjectName("btnInputString")
        self.gridLayout_3.addWidget(self.btnInputString, 0, 0, 1, 1)
        self.btnInputInteger = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInputInteger.setObjectName("btnInputInteger")
        self.gridLayout_3.addWidget(self.btnInputInteger, 0, 1, 1, 1)
        self.inputFloat = QtWidgets.QPushButton(self.groupBox_3)
        self.inputFloat.setObjectName("inputFloat")
        self.gridLayout_3.addWidget(self.inputFloat, 1, 0, 1, 1)
        self.btnItem = QtWidgets.QPushButton(self.groupBox_3)
        self.btnItem.setObjectName("btnItem")
        self.gridLayout_3.addWidget(self.btnItem, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "standard dialog"))
        self.btnOpenMoreFile.setText(_translate("Dialog", "open more files"))
        self.btnFont.setText(_translate("Dialog", "select font"))
        self.btnSelectDirection.setText(_translate("Dialog", "select direction"))
        self.btnOpenFile.setText(_translate("Dialog", "open file"))
        self.btnSave.setText(_translate("Dialog", "save"))
        self.btnColor.setText(_translate("Dialog", "select color"))
        self.btnProgress.setText(_translate("Dialog", "progress"))
        self.groupBox_2.setTitle(_translate("Dialog", "message box"))
        self.btnInfo.setText(_translate("Dialog", "information"))
        self.btnCritical.setText(_translate("Dialog", "critical"))
        self.btnWarning.setText(_translate("Dialog", "warning"))
        self.btnQuestion.setText(_translate("Dialog", "question"))
        self.btnAbout.setText(_translate("Dialog", "about"))
        self.pushButton.setText(_translate("Dialog", "aboutQt"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_3.setTitle(_translate("Dialog", "Input dialog"))
        self.btnExit.setText(_translate("Dialog", "exit"))
        self.btnClear.setText(_translate("Dialog", "clear"))
        self.btnInputString.setText(_translate("Dialog", "input string"))
        self.btnInputInteger.setText(_translate("Dialog", "input integer"))
        self.inputFloat.setText(_translate("Dialog", "input float"))
        self.btnItem.setText(_translate("Dialog", "item "))
import res_rc
