# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiorecorder.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioRecorder(object):
    def setupUi(self, AudioRecorder):
        AudioRecorder.setObjectName("AudioRecorder")
        AudioRecorder.resize(1000, 800)
        self.centralWidget = QtWidgets.QWidget(AudioRecorder)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnExport = QtWidgets.QPushButton(self.widget)
        self.btnExport.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/104.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExport.setIcon(icon)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout.addWidget(self.btnExport)
        self.exportLineEdit = QtWidgets.QLineEdit(self.widget)
        self.exportLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.exportLineEdit.setObjectName("exportLineEdit")
        self.horizontalLayout.addWidget(self.exportLineEdit)
        self.labelTime = QtWidgets.QLabel(self.widget)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout.addWidget(self.labelTime)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxEquip = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxEquip.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxEquip.setObjectName("comboBoxEquip")
        self.gridLayout.addWidget(self.comboBoxEquip, 0, 1, 1, 1)
        self.comboBoxChannels = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxChannels.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxChannels.setObjectName("comboBoxChannels")
        self.gridLayout.addWidget(self.comboBoxChannels, 3, 1, 1, 1)
        self.comboBoxSamplingRate = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxSamplingRate.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxSamplingRate.setObjectName("comboBoxSamplingRate")
        self.gridLayout.addWidget(self.comboBoxSamplingRate, 2, 1, 1, 1)
        self.comboBoxEncoding = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxEncoding.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxEncoding.setObjectName("comboBoxEncoding")
        self.gridLayout.addWidget(self.comboBoxEncoding, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.spinBoxBytes = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBoxBytes.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxBytes.setAccelerated(True)
        self.spinBoxBytes.setMaximum(999999999)
        self.spinBoxBytes.setObjectName("spinBoxBytes")
        self.gridLayout_3.addWidget(self.spinBoxBytes, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBoxDuration = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBoxDuration.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxDuration.setWrapping(False)
        self.spinBoxDuration.setFrame(True)
        self.spinBoxDuration.setReadOnly(False)
        self.spinBoxDuration.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxDuration.setSpecialValueText("")
        self.spinBoxDuration.setAccelerated(True)
        self.spinBoxDuration.setMaximum(999999999)
        self.spinBoxDuration.setObjectName("spinBoxDuration")
        self.gridLayout_3.addWidget(self.spinBoxDuration, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.spinBoxFPS = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBoxFPS.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxFPS.setMaximum(9999999)
        self.spinBoxFPS.setObjectName("spinBoxFPS")
        self.gridLayout_3.addWidget(self.spinBoxFPS, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.spinBoxSample = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBoxSample.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxSample.setMaximum(999999999)
        self.spinBoxSample.setObjectName("spinBoxSample")
        self.gridLayout_3.addWidget(self.spinBoxSample, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.radioButtonFixedQuality = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonFixedQuality.setObjectName("radioButtonFixedQuality")
        self.gridLayout_2.addWidget(self.radioButtonFixedQuality, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.comboBoxBiteRate = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBiteRate.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxBiteRate.setObjectName("comboBoxBiteRate")
        self.gridLayout_2.addWidget(self.comboBoxBiteRate, 1, 1, 1, 1)
        self.radioButtonBitRate = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonBitRate.setObjectName("radioButtonBitRate")
        self.gridLayout_2.addWidget(self.radioButtonBitRate, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.spinBoxChannelCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxChannelCount.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxChannelCount.setObjectName("spinBoxChannelCount")
        self.gridLayout_4.addWidget(self.spinBoxChannelCount, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 6, 0, 1, 1)
        self.spinBoxSampleSize = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxSampleSize.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxSampleSize.setObjectName("spinBoxSampleSize")
        self.gridLayout_4.addWidget(self.spinBoxSampleSize, 4, 1, 1, 1)
        self.spinBoxSampleRate = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxSampleRate.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxSampleRate.setObjectName("spinBoxSampleRate")
        self.gridLayout_4.addWidget(self.spinBoxSampleRate, 5, 1, 1, 1)
        self.spinBoxBPF = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxBPF.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBoxBPF.setMaximum(999999999)
        self.spinBoxBPF.setObjectName("spinBoxBPF")
        self.gridLayout_4.addWidget(self.spinBoxBPF, 6, 1, 1, 1)
        self.lineEditByteOrder = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditByteOrder.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditByteOrder.setObjectName("lineEditByteOrder")
        self.gridLayout_4.addWidget(self.lineEditByteOrder, 1, 1, 1, 1)
        self.lineEditCodec = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditCodec.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditCodec.setObjectName("lineEditCodec")
        self.gridLayout_4.addWidget(self.lineEditCodec, 2, 1, 1, 1)
        self.lineEditSampleType = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditSampleType.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditSampleType.setObjectName("lineEditSampleType")
        self.gridLayout_4.addWidget(self.lineEditSampleType, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 2, 1, 1, 1)
        AudioRecorder.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(AudioRecorder)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 17))
        self.menuBar.setObjectName("menuBar")
        AudioRecorder.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(AudioRecorder)
        self.mainToolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        AudioRecorder.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(AudioRecorder)
        self.statusBar.setObjectName("statusBar")
        AudioRecorder.setStatusBar(self.statusBar)
        self.actionRecord = QtWidgets.QAction(AudioRecorder)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon1)
        self.actionRecord.setObjectName("actionRecord")
        self.actionPause = QtWidgets.QAction(AudioRecorder)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon2)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(AudioRecorder)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/626.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionExit = QtWidgets.QAction(AudioRecorder)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.mainToolBar.addAction(self.actionRecord)
        self.mainToolBar.addAction(self.actionStop)
        self.mainToolBar.addAction(self.actionPause)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(AudioRecorder)
        self.actionExit.triggered.connect(AudioRecorder.close)
        QtCore.QMetaObject.connectSlotsByName(AudioRecorder)

    def retranslateUi(self, AudioRecorder):
        _translate = QtCore.QCoreApplication.translate
        AudioRecorder.setWindowTitle(_translate("AudioRecorder", "AudioRecorder"))
        self.btnExport.setText(_translate("AudioRecorder", "export"))
        self.labelTime.setText(_translate("AudioRecorder", "record time:"))
        self.groupBox_2.setTitle(_translate("AudioRecorder", "Audio Setting"))
        self.label_2.setText(_translate("AudioRecorder", "equipment"))
        self.label_4.setText(_translate("AudioRecorder", "audio encoding"))
        self.label_5.setText(_translate("AudioRecorder", "sampling rate"))
        self.label_3.setText(_translate("AudioRecorder", "channels"))
        self.groupBox_3.setTitle(_translate("AudioRecorder", "Buffer"))
        self.label_8.setText(_translate("AudioRecorder", "buffer bytes"))
        self.spinBoxBytes.setSuffix(_translate("AudioRecorder", "bytes"))
        self.label_9.setText(_translate("AudioRecorder", "buffer duration"))
        self.spinBoxDuration.setSuffix(_translate("AudioRecorder", "ms"))
        self.label_10.setText(_translate("AudioRecorder", "buffer FPS"))
        self.label_11.setText(_translate("AudioRecorder", "samples"))
        self.groupBox.setTitle(_translate("AudioRecorder", "Encoding"))
        self.radioButtonFixedQuality.setText(_translate("AudioRecorder", "fixed quality"))
        self.radioButtonBitRate.setText(_translate("AudioRecorder", "constant bit rate"))
        self.groupBox_4.setTitle(_translate("AudioRecorder", "Audio Format"))
        self.label_12.setText(_translate("AudioRecorder", "channel count"))
        self.label_13.setText(_translate("AudioRecorder", "byteOrder"))
        self.label_14.setText(_translate("AudioRecorder", "codec"))
        self.label_15.setText(_translate("AudioRecorder", "sampleType"))
        self.label_16.setText(_translate("AudioRecorder", "sampleSize"))
        self.label_17.setText(_translate("AudioRecorder", "sampleRate"))
        self.label_18.setText(_translate("AudioRecorder", "bytesPerFrame"))
        self.spinBoxSampleSize.setSuffix(_translate("AudioRecorder", "bits"))
        self.spinBoxSampleRate.setSuffix(_translate("AudioRecorder", "Hz"))
        self.spinBoxBPF.setSuffix(_translate("AudioRecorder", "bytes"))
        self.actionRecord.setText(_translate("AudioRecorder", "Record"))
        self.actionPause.setText(_translate("AudioRecorder", "Pause"))
        self.actionStop.setText(_translate("AudioRecorder", "Stop"))
        self.actionExit.setText(_translate("AudioRecorder", "Exit"))
import res_rc
