# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTimer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName("Timer")
        Timer.resize(600, 400)
        Timer.setMinimumSize(QtCore.QSize(600, 400))
        Timer.setMaximumSize(QtCore.QSize(600, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(Timer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Timer)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.btnStart = QtWidgets.QPushButton(self.groupBox)
        self.btnStart.setMinimumSize(QtCore.QSize(150, 40))
        self.btnStart.setObjectName("btnStart")
        self.gridLayout.addWidget(self.btnStart, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 40))
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(True)
        self.spinBox.setSpecialValueText("")
        self.spinBox.setAccelerated(True)
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.groupBox)
        self.btnStop.setEnabled(False)
        self.btnStop.setMinimumSize(QtCore.QSize(150, 40))
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 0, 3, 1, 1)
        self.btnSetPeriod = QtWidgets.QPushButton(self.groupBox)
        self.btnSetPeriod.setMinimumSize(QtCore.QSize(0, 40))
        self.btnSetPeriod.setObjectName("btnSetPeriod")
        self.gridLayout.addWidget(self.btnSetPeriod, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Timer)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LCDhour = QtWidgets.QLCDNumber(self.groupBox_2)
        self.LCDhour.setObjectName("LCDhour")
        self.horizontalLayout.addWidget(self.LCDhour)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.LCDminute = QtWidgets.QLCDNumber(self.groupBox_2)
        self.LCDminute.setObjectName("LCDminute")
        self.horizontalLayout.addWidget(self.LCDminute)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.LCDsecond = QtWidgets.QLCDNumber(self.groupBox_2)
        self.LCDsecond.setObjectName("LCDsecond")
        self.horizontalLayout.addWidget(self.LCDsecond)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label = QtWidgets.QLabel(Timer)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Timer)
        QtCore.QMetaObject.connectSlotsByName(Timer)

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Form"))
        self.groupBox.setTitle(_translate("Timer", "Timer"))
        self.btnStart.setText(_translate("Timer", "Start"))
        self.spinBox.setSuffix(_translate("Timer", "ms"))
        self.btnStop.setText(_translate("Timer", "Stop"))
        self.btnSetPeriod.setText(_translate("Timer", "Set Period"))
        self.groupBox_2.setTitle(_translate("Timer", "time now (hh:mm:ss)"))
        self.label_2.setText(_translate("Timer", ":"))
        self.label_3.setText(_translate("Timer", ":"))
        self.label.setText(_translate("Timer", "time fleeting"))
