# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtime.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TIME(object):
    def setupUi(self, TIME):
        TIME.setObjectName("TIME")
        TIME.resize(680, 600)
        TIME.setMinimumSize(QtCore.QSize(600, 600))
        TIME.setBaseSize(QtCore.QSize(461, 291))
        self.gridLayout_2 = QtWidgets.QGridLayout(TIME)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(TIME)
        self.frame.setMinimumSize(QtCore.QSize(600, 600))
        self.frame.setBaseSize(QtCore.QSize(461, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DT = QtWidgets.QGroupBox(self.frame)
        self.DT.setMinimumSize(QtCore.QSize(200, 150))
        self.DT.setObjectName("DT")
        self.gridLayoutWidget = QtWidgets.QWidget(self.DT)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 22, 282, 128))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sting = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sting.setObjectName("sting")
        self.gridLayout.addWidget(self.sting, 0, 2, 1, 1)
        self.setTime = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.setTime.setObjectName("setTime")
        self.gridLayout.addWidget(self.setTime, 2, 2, 1, 1)
        self.Readtime = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Readtime.setEnabled(True)
        self.Readtime.setMinimumSize(QtCore.QSize(0, 0))
        self.Readtime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Readtime.setCheckable(False)
        self.Readtime.setObjectName("Readtime")
        self.gridLayout.addWidget(self.Readtime, 0, 0, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout.addWidget(self.lineEdit_time, 1, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 5, 1, 1, 1)
        self.lineEdit_date = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.gridLayout.addWidget(self.lineEdit_date, 3, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 1, 1)
        self.datetime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.datetime.setObjectName("datetime")
        self.gridLayout.addWidget(self.datetime, 5, 0, 1, 1)
        self.setDatetime = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.setDatetime.setObjectName("setDatetime")
        self.gridLayout.addWidget(self.setDatetime, 6, 2, 1, 1)
        self.date = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date.setObjectName("date")
        self.gridLayout.addWidget(self.date, 3, 0, 1, 1)
        self.lineEdit_datetime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_datetime.setObjectName("lineEdit_datetime")
        self.gridLayout.addWidget(self.lineEdit_datetime, 5, 2, 1, 1)
        self.time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 1, 0, 1, 1)
        self.setDate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.setDate.setObjectName("setDate")
        self.gridLayout.addWidget(self.setDate, 4, 2, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.timeEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.timeEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.timeEdit.setCalendarPopup(True)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.DT, 0, 0, 1, 1)
        self.selectDT = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDT.sizePolicy().hasHeightForWidth())
        self.selectDT.setSizePolicy(sizePolicy)
        self.selectDT.setMinimumSize(QtCore.QSize(200, 0))
        self.selectDT.setObjectName("selectDT")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.selectDT)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 302, 330))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.selectDate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.selectDate.setObjectName("selectDate")
        self.gridLayout_3.addWidget(self.selectDate, 0, 0, 1, 1)
        self.lineEdit_select = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_select.setObjectName("lineEdit_select")
        self.gridLayout_3.addWidget(self.lineEdit_select, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.calendar = QtWidgets.QCalendarWidget(self.verticalLayoutWidget)
        self.calendar.setMinimumSize(QtCore.QSize(300, 300))
        self.calendar.setFirstDayOfWeek(QtCore.Qt.Sunday)
        self.calendar.setGridVisible(True)
        self.calendar.setObjectName("calendar")
        self.verticalLayout.addWidget(self.calendar)
        self.gridLayout_4.addWidget(self.selectDT, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(TIME)
        QtCore.QMetaObject.connectSlotsByName(TIME)

    def retranslateUi(self, TIME):
        _translate = QtCore.QCoreApplication.translate
        TIME.setWindowTitle(_translate("TIME", "Form"))
        self.DT.setTitle(_translate("TIME", "DT"))
        self.sting.setText(_translate("TIME", "string"))
        self.setTime.setText(_translate("TIME", "set time"))
        self.Readtime.setText(_translate("TIME", "Read time"))
        self.datetime.setText(_translate("TIME", "datetime"))
        self.setDatetime.setText(_translate("TIME", "set datetime"))
        self.date.setText(_translate("TIME", "date"))
        self.time.setText(_translate("TIME", "time"))
        self.setDate.setText(_translate("TIME", "set date"))
        self.selectDT.setTitle(_translate("TIME", "SELECT DT"))
        self.selectDate.setText(_translate("TIME", "select date"))
