# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relationtable.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_relationTable(object):
    def setupUi(self, relationTable):
        relationTable.setObjectName("relationTable")
        relationTable.resize(800, 600)
        relationTable.setMinimumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(relationTable)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.centralWidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        relationTable.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(relationTable)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menuBar.setObjectName("menuBar")
        relationTable.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(relationTable)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        relationTable.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(relationTable)
        self.statusBar.setObjectName("statusBar")
        relationTable.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(relationTable)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/open3.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlus = QtWidgets.QAction(relationTable)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlus.setIcon(icon1)
        self.actionPlus.setObjectName("actionPlus")
        self.actionInsert = QtWidgets.QAction(relationTable)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/306.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert.setIcon(icon2)
        self.actionInsert.setObjectName("actionInsert")
        self.actionDelete = QtWidgets.QAction(relationTable)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon3)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSave = QtWidgets.QAction(relationTable)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/save1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtWidgets.QAction(relationTable)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/ubdo.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon5)
        self.actionUndo.setObjectName("actionUndo")
        self.actionList = QtWidgets.QAction(relationTable)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/124.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionList.setIcon(icon6)
        self.actionList.setObjectName("actionList")
        self.actionExit = QtWidgets.QAction(relationTable)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionPlus)
        self.mainToolBar.addAction(self.actionInsert)
        self.mainToolBar.addAction(self.actionDelete)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addAction(self.actionUndo)
        self.mainToolBar.addAction(self.actionList)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(relationTable)
        self.actionExit.triggered.connect(relationTable.close)
        QtCore.QMetaObject.connectSlotsByName(relationTable)

    def retranslateUi(self, relationTable):
        _translate = QtCore.QCoreApplication.translate
        relationTable.setWindowTitle(_translate("relationTable", "relationTable"))
        self.actionOpen.setText(_translate("relationTable", "Open"))
        self.actionPlus.setText(_translate("relationTable", "Plus"))
        self.actionInsert.setText(_translate("relationTable", "Insert"))
        self.actionDelete.setText(_translate("relationTable", "Delete"))
        self.actionSave.setText(_translate("relationTable", "Save"))
        self.actionUndo.setText(_translate("relationTable", "Undo"))
        self.actionList.setText(_translate("relationTable", "List"))
        self.actionExit.setText(_translate("relationTable", "Exit"))
import res_rc
