# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablewidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_widget(object):
    def setupUi(self, table_widget):
        table_widget.setObjectName("table_widget")
        table_widget.resize(1000, 600)
        table_widget.setMinimumSize(QtCore.QSize(1000, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(table_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(table_widget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnClear = QtWidgets.QPushButton(self.widget)
        self.btnClear.setMinimumSize(QtCore.QSize(0, 30))
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 4, 1, 1, 1)
        self.btnInsertRow = QtWidgets.QPushButton(self.widget)
        self.btnInsertRow.setMinimumSize(QtCore.QSize(0, 30))
        self.btnInsertRow.setObjectName("btnInsertRow")
        self.gridLayout.addWidget(self.btnInsertRow, 3, 0, 1, 1)
        self.rbGridSelect = QtWidgets.QRadioButton(self.widget)
        self.rbGridSelect.setObjectName("rbGridSelect")
        self.gridLayout.addWidget(self.rbGridSelect, 9, 1, 1, 1)
        self.btnAddRow = QtWidgets.QPushButton(self.widget)
        self.btnAddRow.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAddRow.setObjectName("btnAddRow")
        self.gridLayout.addWidget(self.btnAddRow, 3, 1, 1, 1)
        self.cbEditable = QtWidgets.QCheckBox(self.widget)
        self.cbEditable.setObjectName("cbEditable")
        self.gridLayout.addWidget(self.cbEditable, 7, 0, 1, 1)
        self.rbRowSelect = QtWidgets.QRadioButton(self.widget)
        self.rbRowSelect.setObjectName("rbRowSelect")
        self.gridLayout.addWidget(self.rbRowSelect, 9, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.widget)
        self.btnDelete.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 4, 0, 1, 1)
        self.btnSetTitle = QtWidgets.QPushButton(self.widget)
        self.btnSetTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSetTitle.setObjectName("btnSetTitle")
        self.gridLayout.addWidget(self.btnSetTitle, 0, 0, 1, 2)
        self.btnAutoWidth = QtWidgets.QPushButton(self.widget)
        self.btnAutoWidth.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAutoWidth.setObjectName("btnAutoWidth")
        self.gridLayout.addWidget(self.btnAutoWidth, 5, 1, 1, 1)
        self.btnInitialize = QtWidgets.QPushButton(self.widget)
        self.btnInitialize.setMinimumSize(QtCore.QSize(0, 30))
        self.btnInitialize.setObjectName("btnInitialize")
        self.gridLayout.addWidget(self.btnInitialize, 2, 0, 1, 2)
        self.cbStripe = QtWidgets.QCheckBox(self.widget)
        self.cbStripe.setObjectName("cbStripe")
        self.gridLayout.addWidget(self.cbStripe, 7, 1, 1, 1)
        self.btnContent2text = QtWidgets.QPushButton(self.widget)
        self.btnContent2text.setMinimumSize(QtCore.QSize(0, 30))
        self.btnContent2text.setObjectName("btnContent2text")
        self.gridLayout.addWidget(self.btnContent2text, 6, 0, 1, 2)
        self.cbHeadTitle = QtWidgets.QCheckBox(self.widget)
        self.cbHeadTitle.setObjectName("cbHeadTitle")
        self.gridLayout.addWidget(self.cbHeadTitle, 8, 0, 1, 1)
        self.cbColumnTitle = QtWidgets.QCheckBox(self.widget)
        self.cbColumnTitle.setObjectName("cbColumnTitle")
        self.gridLayout.addWidget(self.cbColumnTitle, 8, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.btnAutoHeight = QtWidgets.QPushButton(self.widget)
        self.btnAutoHeight.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAutoHeight.setObjectName("btnAutoHeight")
        self.gridLayout.addWidget(self.btnAutoHeight, 5, 0, 1, 1)
        self.btnSetRow = QtWidgets.QPushButton(self.widget)
        self.btnSetRow.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSetRow.setObjectName("btnSetRow")
        self.gridLayout.addWidget(self.btnSetRow, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(table_widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(table_widget)
        QtCore.QMetaObject.connectSlotsByName(table_widget)

    def retranslateUi(self, table_widget):
        _translate = QtCore.QCoreApplication.translate
        table_widget.setWindowTitle(_translate("table_widget", "table"))
        self.btnClear.setText(_translate("table_widget", "clear"))
        self.btnInsertRow.setText(_translate("table_widget", "insert row"))
        self.rbGridSelect.setText(_translate("table_widget", "grid select"))
        self.btnAddRow.setText(_translate("table_widget", "add row"))
        self.cbEditable.setText(_translate("table_widget", "editable"))
        self.rbRowSelect.setText(_translate("table_widget", "row select"))
        self.btnDelete.setText(_translate("table_widget", "delete"))
        self.btnSetTitle.setText(_translate("table_widget", "set title"))
        self.btnAutoWidth.setText(_translate("table_widget", "auto width"))
        self.btnInitialize.setText(_translate("table_widget", "Initialize"))
        self.cbStripe.setText(_translate("table_widget", "stripe"))
        self.btnContent2text.setText(_translate("table_widget", "content to text"))
        self.cbHeadTitle.setText(_translate("table_widget", "head title"))
        self.cbColumnTitle.setText(_translate("table_widget", "column title"))
        self.btnAutoHeight.setText(_translate("table_widget", "auto height"))
        self.btnSetRow.setText(_translate("table_widget", "set row"))
