# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaPlayer(object):
    def setupUi(self, MediaPlayer):
        MediaPlayer.setObjectName("MediaPlayer")
        MediaPlayer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MediaPlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QVideoWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbtOpen = QtWidgets.QPushButton(self.widget_2)
        self.pbtOpen.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtOpen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtOpen.setIcon(icon)
        self.pbtOpen.setObjectName("pbtOpen")
        self.horizontalLayout.addWidget(self.pbtOpen)
        self.pbtPlay = QtWidgets.QPushButton(self.widget_2)
        self.pbtPlay.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtPlay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/620.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtPlay.setIcon(icon1)
        self.pbtPlay.setObjectName("pbtPlay")
        self.horizontalLayout.addWidget(self.pbtPlay)
        self.pbtPause = QtWidgets.QPushButton(self.widget_2)
        self.pbtPause.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtPause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtPause.setIcon(icon2)
        self.pbtPause.setObjectName("pbtPause")
        self.horizontalLayout.addWidget(self.pbtPause)
        self.pbtStop = QtWidgets.QPushButton(self.widget_2)
        self.pbtStop.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtStop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtStop.setIcon(icon3)
        self.pbtStop.setObjectName("pbtStop")
        self.horizontalLayout.addWidget(self.pbtStop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbtVolume = QtWidgets.QPushButton(self.widget_2)
        self.pbtVolume.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtVolume.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/volumn.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtVolume.setIcon(icon4)
        self.pbtVolume.setObjectName("pbtVolume")
        self.horizontalLayout.addWidget(self.pbtVolume)
        self.SliderVolume = QtWidgets.QSlider(self.widget_2)
        self.SliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.SliderVolume.setObjectName("SliderVolume")
        self.horizontalLayout.addWidget(self.SliderVolume)
        self.pbtFull = QtWidgets.QPushButton(self.widget_2)
        self.pbtFull.setMinimumSize(QtCore.QSize(50, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/237.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtFull.setIcon(icon5)
        self.pbtFull.setObjectName("pbtFull")
        self.horizontalLayout.addWidget(self.pbtFull)
        self.pbtExit = QtWidgets.QPushButton(self.widget_2)
        self.pbtExit.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtExit.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtExit.setIcon(icon6)
        self.pbtExit.setObjectName("pbtExit")
        self.horizontalLayout.addWidget(self.pbtExit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayout.setStretch(5, 2)
        self.horizontalLayout.setStretch(6, 1)
        self.horizontalLayout.setStretch(7, 3)
        self.horizontalLayout.setStretch(8, 2)
        self.horizontalLayout.setStretch(9, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.labelFile = QtWidgets.QLabel(self.widget_3)
        self.labelFile.setText("")
        self.labelFile.setObjectName("labelFile")
        self.gridLayout.addWidget(self.labelFile, 0, 0, 1, 1)
        self.labelTime = QtWidgets.QLabel(self.widget_3)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout.addWidget(self.labelTime, 1, 2, 1, 1)
        self.SliderProgress = QtWidgets.QSlider(self.widget_3)
        self.SliderProgress.setOrientation(QtCore.Qt.Horizontal)
        self.SliderProgress.setObjectName("SliderProgress")
        self.gridLayout.addWidget(self.SliderProgress, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        MediaPlayer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MediaPlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        MediaPlayer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MediaPlayer)
        self.statusbar.setObjectName("statusbar")
        MediaPlayer.setStatusBar(self.statusbar)

        self.retranslateUi(MediaPlayer)
        self.pbtExit.clicked.connect(MediaPlayer.close)
        QtCore.QMetaObject.connectSlotsByName(MediaPlayer)

    def retranslateUi(self, MediaPlayer):
        _translate = QtCore.QCoreApplication.translate
        MediaPlayer.setWindowTitle(_translate("MediaPlayer", "MainWindow"))
        self.pbtFull.setText(_translate("MediaPlayer", "Full"))
        self.labelTime.setText(_translate("MediaPlayer", "0:00"))
from QVideoWidget import QVideoWidget
import res_rc
