# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treewidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TreeWidget(object):
    def setupUi(self, TreeWidget):
        TreeWidget.setObjectName("TreeWidget")
        TreeWidget.resize(1100, 600)
        TreeWidget.setMinimumSize(QtCore.QSize(1100, 600))
        self.centralWidget = QtWidgets.QWidget(TreeWidget)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 817, 505))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        TreeWidget.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(TreeWidget)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 17))
        self.menuBar.setObjectName("menuBar")
        self.menucatalogue_tree = QtWidgets.QMenu(self.menuBar)
        self.menucatalogue_tree.setObjectName("menucatalogue_tree")
        self.menuview = QtWidgets.QMenu(self.menuBar)
        self.menuview.setObjectName("menuview")
        TreeWidget.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(TreeWidget)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        TreeWidget.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TreeWidget)
        self.statusBar.setObjectName("statusBar")
        TreeWidget.setStatusBar(self.statusBar)
        self.dockWidget = QtWidgets.QDockWidget(TreeWidget)
        self.dockWidget.setMinimumSize(QtCore.QSize(80, 80))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setBackground(0, QtGui.QColor(85, 255, 255))
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setBackground(1, QtGui.QColor(255, 255, 0))
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/open3.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/15.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/31.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_2.setIcon(0, icon2)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(150)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setMinimumSectionSize(60)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.treeWidget.header().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        TreeWidget.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionAdd = QtWidgets.QAction(TreeWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/folder1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon3)
        self.actionAdd.setMenuRole(QtWidgets.QAction.AboutQtRole)
        self.actionAdd.setObjectName("actionAdd")
        self.actionAddDocument = QtWidgets.QAction(TreeWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/824.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddDocument.setIcon(icon4)
        self.actionAddDocument.setObjectName("actionAddDocument")
        self.actionDelete = QtWidgets.QAction(TreeWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon5)
        self.actionDelete.setObjectName("actionDelete")
        self.actionTraverse = QtWidgets.QAction(TreeWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/fold.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTraverse.setIcon(icon6)
        self.actionTraverse.setObjectName("actionTraverse")
        self.actionMagnify = QtWidgets.QAction(TreeWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMagnify.setIcon(icon7)
        self.actionMagnify.setObjectName("actionMagnify")
        self.actionMinify = QtWidgets.QAction(TreeWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMinify.setIcon(icon8)
        self.actionMinify.setObjectName("actionMinify")
        self.actionHeight = QtWidgets.QAction(TreeWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/422.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHeight.setIcon(icon9)
        self.actionHeight.setObjectName("actionHeight")
        self.actionWidth = QtWidgets.QAction(TreeWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/424.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWidth.setIcon(icon10)
        self.actionWidth.setObjectName("actionWidth")
        self.actionFloat = QtWidgets.QAction(TreeWidget)
        self.actionFloat.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/814.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFloat.setIcon(icon11)
        self.actionFloat.setObjectName("actionFloat")
        self.actionVisiable = QtWidgets.QAction(TreeWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVisiable.setIcon(icon12)
        self.actionVisiable.setObjectName("actionVisiable")
        self.actionExit = QtWidgets.QAction(TreeWidget)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon13)
        self.actionExit.setObjectName("actionExit")
        self.actionVisible = QtWidgets.QAction(TreeWidget)
        self.actionVisible.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/preview1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVisible.setIcon(icon14)
        self.actionVisible.setObjectName("actionVisible")
        self.menucatalogue_tree.addAction(self.actionAdd)
        self.menucatalogue_tree.addAction(self.actionTraverse)
        self.menucatalogue_tree.addAction(self.actionAddDocument)
        self.menucatalogue_tree.addAction(self.actionDelete)
        self.menucatalogue_tree.addSeparator()
        self.menucatalogue_tree.addAction(self.actionExit)
        self.menuview.addAction(self.actionMagnify)
        self.menuview.addAction(self.actionMinify)
        self.menuview.addAction(self.actionVisiable)
        self.menuview.addSeparator()
        self.menuview.addAction(self.actionHeight)
        self.menuview.addAction(self.actionWidth)
        self.menuview.addSeparator()
        self.menuview.addAction(self.actionVisible)
        self.menuBar.addAction(self.menucatalogue_tree.menuAction())
        self.menuBar.addAction(self.menuview.menuAction())
        self.mainToolBar.addAction(self.actionAdd)
        self.mainToolBar.addAction(self.actionAddDocument)
        self.mainToolBar.addAction(self.actionDelete)
        self.mainToolBar.addAction(self.actionTraverse)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMagnify)
        self.mainToolBar.addAction(self.actionMinify)
        self.mainToolBar.addAction(self.actionVisiable)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionHeight)
        self.mainToolBar.addAction(self.actionWidth)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionFloat)
        self.mainToolBar.addAction(self.actionVisible)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(TreeWidget)
        self.actionExit.triggered.connect(self.treeWidget.close)
        QtCore.QMetaObject.connectSlotsByName(TreeWidget)

    def retranslateUi(self, TreeWidget):
        _translate = QtCore.QCoreApplication.translate
        TreeWidget.setWindowTitle(_translate("TreeWidget", "TreeWidget"))
        self.label.setText(_translate("TreeWidget", "TextLabel"))
        self.menucatalogue_tree.setTitle(_translate("TreeWidget", "catalogue tree"))
        self.menuview.setTitle(_translate("TreeWidget", "view"))
        self.treeWidget.headerItem().setText(0, _translate("TreeWidget", "node"))
        self.treeWidget.headerItem().setText(1, _translate("TreeWidget", "node type"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("TreeWidget", "picture"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("TreeWidget", "picture"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("TreeWidget", "New Item"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("TreeWidget", "picture1"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.actionAdd.setText(_translate("TreeWidget", "Add"))
        self.actionAddDocument.setText(_translate("TreeWidget", "AddDocument"))
        self.actionDelete.setText(_translate("TreeWidget", "Delete"))
        self.actionTraverse.setText(_translate("TreeWidget", "Traverse"))
        self.actionMagnify.setText(_translate("TreeWidget", "Magnify"))
        self.actionMinify.setText(_translate("TreeWidget", "Minify"))
        self.actionHeight.setText(_translate("TreeWidget", "Height"))
        self.actionWidth.setText(_translate("TreeWidget", "Width"))
        self.actionFloat.setText(_translate("TreeWidget", "Float"))
        self.actionVisiable.setText(_translate("TreeWidget", "Actual"))
        self.actionExit.setText(_translate("TreeWidget", "Exit"))
        self.actionVisible.setText(_translate("TreeWidget", "Visible"))
import res_rc
