# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtmysql.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtMySQL(object):
    def setupUi(self, QtMySQL):
        QtMySQL.setObjectName("QtMySQL")
        QtMySQL.resize(1000, 600)
        QtMySQL.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralWidget = QtWidgets.QWidget(QtMySQL)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 1, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioMale = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioMale.setObjectName("radioMale")
        self.gridLayout_2.addWidget(self.radioMale, 0, 0, 1, 1)
        self.radioFemale = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioFemale.setObjectName("radioFemale")
        self.gridLayout_2.addWidget(self.radioFemale, 0, 1, 1, 1)
        self.radioAll = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioAll.setObjectName("radioAll")
        self.gridLayout_2.addWidget(self.radioAll, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxArrange = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxArrange.setObjectName("comboBoxArrange")
        self.gridLayout.addWidget(self.comboBoxArrange, 0, 1, 1, 2)
        self.radioAscend = QtWidgets.QRadioButton(self.groupBox)
        self.radioAscend.setObjectName("radioAscend")
        self.gridLayout.addWidget(self.radioAscend, 1, 0, 1, 2)
        self.radioDescend = QtWidgets.QRadioButton(self.groupBox)
        self.radioDescend.setObjectName("radioDescend")
        self.gridLayout.addWidget(self.radioDescend, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 2)
        self.spinBoxAge = QtWidgets.QSpinBox(self.widget_2)
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.gridLayout_4.addWidget(self.spinBoxAge, 9, 2, 1, 2)
        self.comboBoxSex = QtWidgets.QComboBox(self.widget_2)
        self.comboBoxSex.setObjectName("comboBoxSex")
        self.gridLayout_4.addWidget(self.comboBoxSex, 6, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 7, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 9, 0, 1, 2)
        self.doubleSpinBoxSalary = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.doubleSpinBoxSalary.setObjectName("doubleSpinBoxSalary")
        self.gridLayout_4.addWidget(self.doubleSpinBoxSalary, 10, 2, 1, 2)
        self.lineEditName = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout_4.addWidget(self.lineEditName, 4, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 8, 0, 1, 2)
        self.spinBoxID = QtWidgets.QSpinBox(self.widget_2)
        self.spinBoxID.setObjectName("spinBoxID")
        self.gridLayout_4.addWidget(self.spinBoxID, 1, 2, 1, 2)
        self.lineEditCountry = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditCountry.setObjectName("lineEditCountry")
        self.gridLayout_4.addWidget(self.lineEditCountry, 8, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 10, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_4.addWidget(self.dateEdit, 7, 2, 1, 2)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.centralWidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabImage = QtWidgets.QLabel(self.widget_4)
        self.LabImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LabImage.setObjectName("LabImage")
        self.horizontalLayout.addWidget(self.LabImage)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        QtMySQL.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(QtMySQL)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 17))
        self.menuBar.setObjectName("menuBar")
        QtMySQL.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(QtMySQL)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        QtMySQL.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(QtMySQL)
        self.statusBar.setObjectName("statusBar")
        QtMySQL.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(QtMySQL)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/open.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAdd = QtWidgets.QAction(QtMySQL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon1)
        self.actionAdd.setObjectName("actionAdd")
        self.actionInsert = QtWidgets.QAction(QtMySQL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/306.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert.setIcon(icon2)
        self.actionInsert.setObjectName("actionInsert")
        self.actionDelete = QtWidgets.QAction(QtMySQL)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/delete.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon3)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSet_Picture = QtWidgets.QAction(QtMySQL)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/31.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_Picture.setIcon(icon4)
        self.actionSet_Picture.setObjectName("actionSet_Picture")
        self.actionClear_picture = QtWidgets.QAction(QtMySQL)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/103.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_picture.setIcon(icon5)
        self.actionClear_picture.setObjectName("actionClear_picture")
        self.actionBonus = QtWidgets.QAction(QtMySQL)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/724.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBonus.setIcon(icon6)
        self.actionBonus.setObjectName("actionBonus")
        self.actionSave = QtWidgets.QAction(QtMySQL)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/save.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtWidgets.QAction(QtMySQL)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/undo.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon8)
        self.actionUndo.setObjectName("actionUndo")
        self.actionExit = QtWidgets.QAction(QtMySQL)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon9)
        self.actionExit.setObjectName("actionExit")
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionAdd)
        self.mainToolBar.addAction(self.actionInsert)
        self.mainToolBar.addAction(self.actionDelete)
        self.mainToolBar.addAction(self.actionSet_Picture)
        self.mainToolBar.addAction(self.actionClear_picture)
        self.mainToolBar.addAction(self.actionBonus)
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addAction(self.actionUndo)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)
        self.mainToolBar.addSeparator()

        self.retranslateUi(QtMySQL)
        self.actionExit.triggered.connect(QtMySQL.close)
        QtCore.QMetaObject.connectSlotsByName(QtMySQL)

    def retranslateUi(self, QtMySQL):
        _translate = QtCore.QCoreApplication.translate
        QtMySQL.setWindowTitle(_translate("QtMySQL", "QtMySQL"))
        self.groupBox_2.setTitle(_translate("QtMySQL", "Filter"))
        self.radioMale.setText(_translate("QtMySQL", "male"))
        self.radioFemale.setText(_translate("QtMySQL", "female"))
        self.radioAll.setText(_translate("QtMySQL", "all"))
        self.groupBox.setTitle(_translate("QtMySQL", "arrangement"))
        self.radioAscend.setText(_translate("QtMySQL", "ascend"))
        self.radioDescend.setText(_translate("QtMySQL", "descend"))
        self.label.setText(_translate("QtMySQL", "arrange"))
        self.label_3.setText(_translate("QtMySQL", "Name"))
        self.label_6.setText(_translate("QtMySQL", "Sex"))
        self.label_2.setText(_translate("QtMySQL", "ID"))
        self.label_4.setText(_translate("QtMySQL", "Birth"))
        self.label_5.setText(_translate("QtMySQL", "Age"))
        self.label_7.setText(_translate("QtMySQL", "Country"))
        self.label_8.setText(_translate("QtMySQL", "Salary"))
        self.LabImage.setText(_translate("QtMySQL", "picture"))
        self.actionOpen.setText(_translate("QtMySQL", "Open"))
        self.actionAdd.setText(_translate("QtMySQL", "Add"))
        self.actionInsert.setText(_translate("QtMySQL", "Insert"))
        self.actionDelete.setText(_translate("QtMySQL", "Delete"))
        self.actionSet_Picture.setText(_translate("QtMySQL", "Set Picture"))
        self.actionClear_picture.setText(_translate("QtMySQL", "Clear picture"))
        self.actionBonus.setText(_translate("QtMySQL", "Bonus"))
        self.actionSave.setText(_translate("QtMySQL", "Save"))
        self.actionUndo.setText(_translate("QtMySQL", "Undo"))
        self.actionExit.setText(_translate("QtMySQL", "Exit"))
import res_rc
