# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 300)
        self.centralWidget = QtWidgets.QWidget(Widget)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBtn = QtWidgets.QPushButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/image/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftBtn.setIcon(icon)
        self.leftBtn.setCheckable(True)
        self.leftBtn.setAutoExclusive(True)
        self.leftBtn.setFlat(True)
        self.leftBtn.setObjectName("leftBtn")
        self.horizontalLayout.addWidget(self.leftBtn)
        self.middleBtn = QtWidgets.QPushButton(self.centralWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/image/middle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.middleBtn.setIcon(icon1)
        self.middleBtn.setCheckable(True)
        self.middleBtn.setAutoExclusive(True)
        self.middleBtn.setFlat(True)
        self.middleBtn.setObjectName("middleBtn")
        self.horizontalLayout.addWidget(self.middleBtn)
        self.rightBtn = QtWidgets.QPushButton(self.centralWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/image/right.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightBtn.setIcon(icon2)
        self.rightBtn.setCheckable(True)
        self.rightBtn.setAutoExclusive(True)
        self.rightBtn.setFlat(True)
        self.rightBtn.setObjectName("rightBtn")
        self.horizontalLayout.addWidget(self.rightBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boldBtn = QtWidgets.QPushButton(self.centralWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/image/B.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldBtn.setIcon(icon3)
        self.boldBtn.setCheckable(True)
        self.boldBtn.setObjectName("boldBtn")
        self.horizontalLayout_2.addWidget(self.boldBtn)
        self.italicBtn = QtWidgets.QPushButton(self.centralWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/image/I.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicBtn.setIcon(icon4)
        self.italicBtn.setCheckable(True)
        self.italicBtn.setObjectName("italicBtn")
        self.horizontalLayout_2.addWidget(self.italicBtn)
        self.underlineBtn = QtWidgets.QPushButton(self.centralWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/image/U.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineBtn.setIcon(icon5)
        self.underlineBtn.setCheckable(True)
        self.underlineBtn.setObjectName("underlineBtn")
        self.horizontalLayout_2.addWidget(self.underlineBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rendonly = QtWidgets.QCheckBox(self.centralWidget)
        self.rendonly.setObjectName("rendonly")
        self.horizontalLayout_3.addWidget(self.rendonly)
        self.enabled = QtWidgets.QCheckBox(self.centralWidget)
        self.enabled.setObjectName("enabled")
        self.horizontalLayout_3.addWidget(self.enabled)
        self.clearbtn = QtWidgets.QCheckBox(self.centralWidget)
        self.clearbtn.setObjectName("clearbtn")
        self.horizontalLayout_3.addWidget(self.clearbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(24)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        Widget.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Widget)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 17))
        self.menuBar.setObjectName("menuBar")
        Widget.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Widget)
        self.mainToolBar.setObjectName("mainToolBar")
        Widget.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Widget)
        self.statusBar.setObjectName("statusBar")
        Widget.setStatusBar(self.statusBar)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.leftBtn.setText(_translate("Widget", "Left"))
        self.middleBtn.setText(_translate("Widget", "Middle"))
        self.rightBtn.setText(_translate("Widget", "Right"))
        self.boldBtn.setText(_translate("Widget", "Bold"))
        self.italicBtn.setText(_translate("Widget", "Italic"))
        self.underlineBtn.setText(_translate("Widget", "Underline"))
        self.rendonly.setText(_translate("Widget", "Rendonly"))
        self.enabled.setText(_translate("Widget", "Enabled"))
        self.clearbtn.setText(_translate("Widget", "ClearButtonEnable"))
        self.textEdit.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bahnschrift SemiCondensed\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hello world</p></body></html>"))
import res_rc
