# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlquery.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SqlQuery(object):
    def setupUi(self, SqlQuery):
        SqlQuery.setObjectName("SqlQuery")
        SqlQuery.resize(982, 521)
        self.centralWidget = QtWidgets.QWidget(SqlQuery)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 2)
        self.spinBoxAge = QtWidgets.QSpinBox(self.widget_2)
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.gridLayout_4.addWidget(self.spinBoxAge, 9, 2, 1, 2)
        self.comboBoxSex = QtWidgets.QComboBox(self.widget_2)
        self.comboBoxSex.setObjectName("comboBoxSex")
        self.gridLayout_4.addWidget(self.comboBoxSex, 6, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 7, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 9, 0, 1, 2)
        self.doubleSpinBoxSalary = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.doubleSpinBoxSalary.setObjectName("doubleSpinBoxSalary")
        self.gridLayout_4.addWidget(self.doubleSpinBoxSalary, 10, 2, 1, 2)
        self.lineEditName = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout_4.addWidget(self.lineEditName, 4, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 8, 0, 1, 2)
        self.spinBoxID = QtWidgets.QSpinBox(self.widget_2)
        self.spinBoxID.setObjectName("spinBoxID")
        self.gridLayout_4.addWidget(self.spinBoxID, 1, 2, 1, 2)
        self.lineEditCountry = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditCountry.setObjectName("lineEditCountry")
        self.gridLayout_4.addWidget(self.lineEditCountry, 8, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 10, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_4.addWidget(self.dateEdit, 7, 2, 1, 2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.LabImage = QtWidgets.QLabel(self.centralWidget)
        self.LabImage.setText("")
        self.LabImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LabImage.setObjectName("LabImage")
        self.horizontalLayout.addWidget(self.LabImage)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        SqlQuery.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(SqlQuery)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 982, 17))
        self.menuBar.setObjectName("menuBar")
        SqlQuery.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(SqlQuery)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        SqlQuery.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(SqlQuery)
        self.statusBar.setObjectName("statusBar")
        SqlQuery.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(SqlQuery)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/open3.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFirst = QtWidgets.QAction(SqlQuery)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/308.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirst.setIcon(icon1)
        self.actionFirst.setObjectName("actionFirst")
        self.actionBack = QtWidgets.QAction(SqlQuery)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/310.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon2)
        self.actionBack.setObjectName("actionBack")
        self.actionNext = QtWidgets.QAction(SqlQuery)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/312.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon3)
        self.actionNext.setObjectName("actionNext")
        self.actionLast = QtWidgets.QAction(SqlQuery)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/314.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLast.setIcon(icon4)
        self.actionLast.setObjectName("actionLast")
        self.actionExit = QtWidgets.QAction(SqlQuery)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionFirst)
        self.mainToolBar.addAction(self.actionBack)
        self.mainToolBar.addAction(self.actionNext)
        self.mainToolBar.addAction(self.actionLast)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(SqlQuery)
        self.actionExit.triggered.connect(SqlQuery.close)
        QtCore.QMetaObject.connectSlotsByName(SqlQuery)

    def retranslateUi(self, SqlQuery):
        _translate = QtCore.QCoreApplication.translate
        SqlQuery.setWindowTitle(_translate("SqlQuery", "SqlQuery"))
        self.label_3.setText(_translate("SqlQuery", "Name"))
        self.label_6.setText(_translate("SqlQuery", "Sex"))
        self.label_2.setText(_translate("SqlQuery", "ID"))
        self.label_4.setText(_translate("SqlQuery", "Birth"))
        self.label_5.setText(_translate("SqlQuery", "Age"))
        self.label_7.setText(_translate("SqlQuery", "Country"))
        self.label_8.setText(_translate("SqlQuery", "Salary"))
        self.actionOpen.setText(_translate("SqlQuery", "Open"))
        self.actionFirst.setText(_translate("SqlQuery", "First"))
        self.actionBack.setText(_translate("SqlQuery", "Back"))
        self.actionNext.setText(_translate("SqlQuery", "Next"))
        self.actionLast.setText(_translate("SqlQuery", "Last"))
        self.actionExit.setText(_translate("SqlQuery", "Exit"))
import res_rc
