# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dragwidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DragWidget(object):
    def setupUi(self, DragWidget):
        DragWidget.setObjectName("DragWidget")
        DragWidget.resize(453, 282)
        self.gridLayout_2 = QtWidgets.QGridLayout(DragWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gbObjectsetting = QtWidgets.QGroupBox(DragWidget)
        self.gbObjectsetting.setObjectName("gbObjectsetting")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbObjectsetting)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbtListSource = QtWidgets.QRadioButton(self.gbObjectsetting)
        self.rbtListSource.setObjectName("rbtListSource")
        self.verticalLayout.addWidget(self.rbtListSource)
        self.rbtListWidget = QtWidgets.QRadioButton(self.gbObjectsetting)
        self.rbtListWidget.setObjectName("rbtListWidget")
        self.verticalLayout.addWidget(self.rbtListWidget)
        self.rbtTreeWidget = QtWidgets.QRadioButton(self.gbObjectsetting)
        self.rbtTreeWidget.setObjectName("rbtTreeWidget")
        self.verticalLayout.addWidget(self.rbtTreeWidget)
        self.rbtTableWidget = QtWidgets.QRadioButton(self.gbObjectsetting)
        self.rbtTableWidget.setObjectName("rbtTableWidget")
        self.verticalLayout.addWidget(self.rbtTableWidget)
        self.gridLayout_2.addWidget(self.gbObjectsetting, 0, 0, 1, 1)
        self.gbParametersetting = QtWidgets.QGroupBox(DragWidget)
        self.gbParametersetting.setObjectName("gbParametersetting")
        self.gridLayout = QtWidgets.QGridLayout(self.gbParametersetting)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(self.gbParametersetting)
        self.checkBox_1.setObjectName("checkBox_1")
        self.gridLayout.addWidget(self.checkBox_1, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gbParametersetting)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gbParametersetting)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.gbParametersetting)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbParametersetting)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gbParametersetting)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.gbParametersetting, 0, 1, 1, 3)
        self.gbListSource = QtWidgets.QGroupBox(DragWidget)
        self.gbListSource.setObjectName("gbListSource")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbListSource)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listSource = QtWidgets.QListWidget(self.gbListSource)
        self.listSource.setObjectName("listSource")
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listSource.addItem(item)
        self.horizontalLayout.addWidget(self.listSource)
        self.gridLayout_2.addWidget(self.gbListSource, 1, 0, 1, 1)
        self.gbListWidget = QtWidgets.QGroupBox(DragWidget)
        self.gbListWidget.setObjectName("gbListWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbListWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.gbListWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.gridLayout_2.addWidget(self.gbListWidget, 1, 1, 1, 1)
        self.gbTreeWidget = QtWidgets.QGroupBox(DragWidget)
        self.gbTreeWidget.setObjectName("gbTreeWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbTreeWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.gbTreeWidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.gridLayout_2.addWidget(self.gbTreeWidget, 1, 2, 1, 1)
        self.gbTableWidget = QtWidgets.QGroupBox(DragWidget)
        self.gbTableWidget.setObjectName("gbTableWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbTableWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.gbTableWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.gridLayout_2.addWidget(self.gbTableWidget, 1, 3, 1, 1)
        self.actiona = QtWidgets.QAction(DragWidget)
        self.actiona.setObjectName("actiona")
        self.actionb = QtWidgets.QAction(DragWidget)
        self.actionb.setObjectName("actionb")
        self.actionc = QtWidgets.QAction(DragWidget)
        self.actionc.setObjectName("actionc")

        self.retranslateUi(DragWidget)
        QtCore.QMetaObject.connectSlotsByName(DragWidget)

    def retranslateUi(self, DragWidget):
        _translate = QtCore.QCoreApplication.translate
        DragWidget.setWindowTitle(_translate("DragWidget", "DragWidget"))
        self.gbObjectsetting.setTitle(_translate("DragWidget", "object setting"))
        self.rbtListSource.setText(_translate("DragWidget", "listSource"))
        self.rbtListWidget.setText(_translate("DragWidget", "listWidget"))
        self.rbtTreeWidget.setText(_translate("DragWidget", "treeWidget"))
        self.rbtTableWidget.setText(_translate("DragWidget", "tableWidget"))
        self.gbParametersetting.setTitle(_translate("DragWidget", "parameter setting"))
        self.checkBox_1.setText(_translate("DragWidget", "acceptDrags"))
        self.checkBox_2.setText(_translate("DragWidget", "dragEnabled"))
        self.label_1.setText(_translate("DragWidget", "dragDropMode"))
        self.label_2.setText(_translate("DragWidget", "defaultDropAction"))
        self.gbListSource.setTitle(_translate("DragWidget", "listSource"))
        __sortingEnabled = self.listSource.isSortingEnabled()
        self.listSource.setSortingEnabled(False)
        item = self.listSource.item(0)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(1)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(2)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(3)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(4)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(5)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(6)
        item.setText(_translate("DragWidget", "New Item"))
        item = self.listSource.item(7)
        item.setText(_translate("DragWidget", "New Item"))
        self.listSource.setSortingEnabled(__sortingEnabled)
        self.gbListWidget.setTitle(_translate("DragWidget", "listWidget"))
        self.gbTreeWidget.setTitle(_translate("DragWidget", "treeWidget"))
        self.gbTableWidget.setTitle(_translate("DragWidget", "tableWidget"))
        self.actiona.setText(_translate("DragWidget", "a"))
        self.actionb.setText(_translate("DragWidget", "b"))
        self.actionc.setText(_translate("DragWidget", "c"))
