# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painter.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Painter(object):
    def setupUi(self, Painter):
        Painter.setObjectName("Painter")
        Painter.resize(1000, 800)
        Painter.setMinimumSize(QtCore.QSize(1000, 800))
        Painter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtWidgets.QWidget(Painter)
        self.centralWidget.setObjectName("centralWidget")
        Painter.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Painter)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 17))
        self.menuBar.setObjectName("menuBar")
        Painter.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Painter)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        Painter.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Painter)
        self.statusBar.setObjectName("statusBar")
        Painter.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(Painter)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        Painter.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionZoomIn = QtWidgets.QAction(Painter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(Painter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon1)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionRestore = QtWidgets.QAction(Painter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/08.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestore.setIcon(icon2)
        self.actionRestore.setObjectName("actionRestore")
        self.actionRotateLeft = QtWidgets.QAction(Painter)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/rotateleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotateLeft.setIcon(icon3)
        self.actionRotateLeft.setObjectName("actionRotateLeft")
        self.actionRotateRight = QtWidgets.QAction(Painter)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/rotateright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotateRight.setIcon(icon4)
        self.actionRotateRight.setObjectName("actionRotateRight")
        self.actionFront = QtWidgets.QAction(Painter)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/528.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFront.setIcon(icon5)
        self.actionFront.setObjectName("actionFront")
        self.actionBack = QtWidgets.QAction(Painter)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/526.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon6)
        self.actionBack.setObjectName("actionBack")
        self.actionGroup = QtWidgets.QAction(Painter)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/UNGROUP.BMP"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGroup.setIcon(icon7)
        self.actionGroup.setObjectName("actionGroup")
        self.actionUngroup = QtWidgets.QAction(Painter)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/281.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUngroup.setIcon(icon8)
        self.actionUngroup.setObjectName("actionUngroup")
        self.actionDelete = QtWidgets.QAction(Painter)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/DELETE.BMP"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon9)
        self.actionDelete.setObjectName("actionDelete")
        self.actionExit = QtWidgets.QAction(Painter)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon10)
        self.actionExit.setObjectName("actionExit")
        self.actionRectangle = QtWidgets.QAction(Painter)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/RECTANGL.BMP"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRectangle.setIcon(icon11)
        self.actionRectangle.setObjectName("actionRectangle")
        self.actionEllipse = QtWidgets.QAction(Painter)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/ELLIPSE.BMP"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEllipse.setIcon(icon12)
        self.actionEllipse.setObjectName("actionEllipse")
        self.actionCircle = QtWidgets.QAction(Painter)
        self.actionCircle.setIcon(icon2)
        self.actionCircle.setObjectName("actionCircle")
        self.actionTriangle = QtWidgets.QAction(Painter)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/Icon1242.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTriangle.setIcon(icon13)
        self.actionTriangle.setObjectName("actionTriangle")
        self.actionTrapezium = QtWidgets.QAction(Painter)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/FREEFORM.BMP"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrapezium.setIcon(icon14)
        self.actionTrapezium.setObjectName("actionTrapezium")
        self.actionLine = QtWidgets.QAction(Painter)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/LINE.BMP"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine.setIcon(icon15)
        self.actionLine.setObjectName("actionLine")
        self.actionText = QtWidgets.QAction(Painter)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/hmsetup.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionText.setIcon(icon16)
        self.actionText.setObjectName("actionText")
        self.mainToolBar.addAction(self.actionZoomIn)
        self.mainToolBar.addAction(self.actionZoomOut)
        self.mainToolBar.addAction(self.actionRestore)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionRotateLeft)
        self.mainToolBar.addAction(self.actionRotateRight)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionFront)
        self.mainToolBar.addAction(self.actionBack)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionGroup)
        self.mainToolBar.addAction(self.actionUngroup)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionDelete)
        self.mainToolBar.addAction(self.actionExit)
        self.toolBar.addAction(self.actionRectangle)
        self.toolBar.addAction(self.actionEllipse)
        self.toolBar.addAction(self.actionCircle)
        self.toolBar.addAction(self.actionTriangle)
        self.toolBar.addAction(self.actionTrapezium)
        self.toolBar.addAction(self.actionLine)
        self.toolBar.addAction(self.actionText)

        self.retranslateUi(Painter)
        self.actionExit.triggered.connect(Painter.close)
        QtCore.QMetaObject.connectSlotsByName(Painter)

    def retranslateUi(self, Painter):
        _translate = QtCore.QCoreApplication.translate
        Painter.setWindowTitle(_translate("Painter", "Painter"))
        self.toolBar.setWindowTitle(_translate("Painter", "toolBar"))
        self.actionZoomIn.setText(_translate("Painter", "ZoomIn"))
        self.actionZoomOut.setText(_translate("Painter", "ZoomOut"))
        self.actionRestore.setText(_translate("Painter", "Restore"))
        self.actionRotateLeft.setText(_translate("Painter", "RotateLeft"))
        self.actionRotateRight.setText(_translate("Painter", "RotateRight"))
        self.actionFront.setText(_translate("Painter", "Front"))
        self.actionBack.setText(_translate("Painter", "Back"))
        self.actionGroup.setText(_translate("Painter", "Group"))
        self.actionUngroup.setText(_translate("Painter", "Ungroup"))
        self.actionDelete.setText(_translate("Painter", "Delete"))
        self.actionExit.setText(_translate("Painter", "Exit"))
        self.actionRectangle.setText(_translate("Painter", "Rectangle"))
        self.actionEllipse.setText(_translate("Painter", "Ellipse"))
        self.actionCircle.setText(_translate("Painter", "Circle"))
        self.actionTriangle.setText(_translate("Painter", "Triangle"))
        self.actionTrapezium.setText(_translate("Painter", "Trapezium"))
        self.actionLine.setText(_translate("Painter", "Line"))
        self.actionText.setText(_translate("Painter", "Text"))
import res_rc
