# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plt_gui(object):
    def setupUi(self, plt_gui):
        plt_gui.setObjectName("plt_gui")
        plt_gui.resize(772, 760)
        self.centralWidget = QtWidgets.QWidget(plt_gui)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.centralWidget)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 378, 569))
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbSuptitle = QtWidgets.QGroupBox(self.page)
        self.gbSuptitle.setCheckable(True)
        self.gbSuptitle.setObjectName("gbSuptitle")
        self.gridLayout = QtWidgets.QGridLayout(self.gbSuptitle)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnTitle = QtWidgets.QPushButton(self.gbSuptitle)
        self.btnTitle.setObjectName("btnTitle")
        self.gridLayout.addWidget(self.btnTitle, 0, 0, 1, 1)
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.gbSuptitle)
        self.spinBoxFontSize.setProperty("value", 16)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.gridLayout.addWidget(self.spinBoxFontSize, 3, 1, 1, 1)
        self.cbBold = QtWidgets.QCheckBox(self.gbSuptitle)
        self.cbBold.setObjectName("cbBold")
        self.gridLayout.addWidget(self.cbBold, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gbSuptitle)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.cbItalic = QtWidgets.QCheckBox(self.gbSuptitle)
        self.cbItalic.setObjectName("cbItalic")
        self.gridLayout.addWidget(self.cbItalic, 3, 3, 1, 1)
        self.btnFontColor = QtWidgets.QPushButton(self.gbSuptitle)
        self.btnFontColor.setObjectName("btnFontColor")
        self.gridLayout.addWidget(self.btnFontColor, 5, 0, 1, 2)
        self.lineEditTitle = QtWidgets.QLineEdit(self.gbSuptitle)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.gridLayout.addWidget(self.lineEditTitle, 0, 1, 1, 3)
        self.btnBackgroundColor = QtWidgets.QPushButton(self.gbSuptitle)
        self.btnBackgroundColor.setObjectName("btnBackgroundColor")
        self.gridLayout.addWidget(self.btnBackgroundColor, 5, 2, 1, 2)
        self.verticalLayout.addWidget(self.gbSuptitle)
        self.gbBackground = QtWidgets.QGroupBox(self.page)
        self.gbBackground.setObjectName("gbBackground")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbBackground)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbShow = QtWidgets.QCheckBox(self.gbBackground)
        self.cbShow.setObjectName("cbShow")
        self.gridLayout_2.addWidget(self.cbShow, 0, 0, 1, 1)
        self.btnSetColor = QtWidgets.QPushButton(self.gbBackground)
        self.btnSetColor.setObjectName("btnSetColor")
        self.gridLayout_2.addWidget(self.btnSetColor, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbBackground)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.cbFigureStyle = QtWidgets.QComboBox(self.gbBackground)
        self.cbFigureStyle.setObjectName("cbFigureStyle")
        self.gridLayout_2.addWidget(self.cbFigureStyle, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbBackground)
        self.gbInterval = QtWidgets.QGroupBox(self.page)
        self.gbInterval.setObjectName("gbInterval")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbInterval)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gbInterval)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbInterval)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gbInterval)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 2, 1, 1)
        self.dsbHspace = QtWidgets.QDoubleSpinBox(self.gbInterval)
        self.dsbHspace.setMaximum(9999.0)
        self.dsbHspace.setSingleStep(0.01)
        self.dsbHspace.setObjectName("dsbHspace")
        self.gridLayout_3.addWidget(self.dsbHspace, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbInterval)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gbInterval)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.dsbBottom = QtWidgets.QDoubleSpinBox(self.gbInterval)
        self.dsbBottom.setMaximum(9999.0)
        self.dsbBottom.setSingleStep(0.01)
        self.dsbBottom.setObjectName("dsbBottom")
        self.gridLayout_3.addWidget(self.dsbBottom, 3, 1, 1, 1)
        self.dsbTop = QtWidgets.QDoubleSpinBox(self.gbInterval)
        self.dsbTop.setMaximum(9999.0)
        self.dsbTop.setSingleStep(0.01)
        self.dsbTop.setObjectName("dsbTop")
        self.gridLayout_3.addWidget(self.dsbTop, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gbInterval)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 2, 1, 1)
        self.dsbWspace = QtWidgets.QDoubleSpinBox(self.gbInterval)
        self.dsbWspace.setMaximum(9999.0)
        self.dsbWspace.setSingleStep(0.01)
        self.dsbWspace.setObjectName("dsbWspace")
        self.gridLayout_3.addWidget(self.dsbWspace, 4, 1, 1, 1)
        self.dsbRight = QtWidgets.QDoubleSpinBox(self.gbInterval)
        self.dsbRight.setMaximum(9999.0)
        self.dsbRight.setSingleStep(0.01)
        self.dsbRight.setObjectName("dsbRight")
        self.gridLayout_3.addWidget(self.dsbRight, 1, 3, 1, 1)
        self.dsbLeft = QtWidgets.QDoubleSpinBox(self.gbInterval)
        self.dsbLeft.setMaximum(9999.0)
        self.dsbLeft.setSingleStep(0.01)
        self.dsbLeft.setObjectName("dsbLeft")
        self.gridLayout_3.addWidget(self.dsbLeft, 1, 1, 1, 1)
        self.btnTightLayout = QtWidgets.QPushButton(self.gbInterval)
        self.btnTightLayout.setObjectName("btnTightLayout")
        self.gridLayout_3.addWidget(self.btnTightLayout, 5, 3, 1, 1)
        self.verticalLayout.addWidget(self.gbInterval)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 378, 569))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbVisible = QtWidgets.QCheckBox(self.page_2)
        self.cbVisible.setObjectName("cbVisible")
        self.verticalLayout_2.addWidget(self.cbVisible)
        self.gbTitle = QtWidgets.QGroupBox(self.page_2)
        self.gbTitle.setCheckable(True)
        self.gbTitle.setObjectName("gbTitle")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbTitle)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBoxfontSize_2 = QtWidgets.QSpinBox(self.gbTitle)
        self.spinBoxfontSize_2.setObjectName("spinBoxfontSize_2")
        self.gridLayout_4.addWidget(self.spinBoxfontSize_2, 1, 1, 1, 1)
        self.cbItalic_2 = QtWidgets.QCheckBox(self.gbTitle)
        self.cbItalic_2.setObjectName("cbItalic_2")
        self.gridLayout_4.addWidget(self.cbItalic_2, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gbTitle)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.btnSetTitle = QtWidgets.QPushButton(self.gbTitle)
        self.btnSetTitle.setObjectName("btnSetTitle")
        self.gridLayout_4.addWidget(self.btnSetTitle, 0, 0, 1, 1)
        self.cbBold_2 = QtWidgets.QCheckBox(self.gbTitle)
        self.cbBold_2.setObjectName("cbBold_2")
        self.gridLayout_4.addWidget(self.cbBold_2, 1, 2, 1, 1)
        self.lineEditPlotTitle = QtWidgets.QLineEdit(self.gbTitle)
        self.lineEditPlotTitle.setObjectName("lineEditPlotTitle")
        self.gridLayout_4.addWidget(self.lineEditPlotTitle, 0, 1, 1, 3)
        self.btnBackgroundColor_2 = QtWidgets.QPushButton(self.gbTitle)
        self.btnBackgroundColor_2.setObjectName("btnBackgroundColor_2")
        self.gridLayout_4.addWidget(self.btnBackgroundColor_2, 2, 2, 1, 2)
        self.btnFontColor_2 = QtWidgets.QPushButton(self.gbTitle)
        self.btnFontColor_2.setObjectName("btnFontColor_2")
        self.gridLayout_4.addWidget(self.btnFontColor_2, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.gbTitle)
        self.gbAppearance = QtWidgets.QGroupBox(self.page_2)
        self.gbAppearance.setCheckable(True)
        self.gbAppearance.setObjectName("gbAppearance")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbAppearance)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cbXgrid = QtWidgets.QCheckBox(self.gbAppearance)
        self.cbXgrid.setObjectName("cbXgrid")
        self.gridLayout_5.addWidget(self.cbXgrid, 1, 0, 1, 1)
        self.cbShow_2 = QtWidgets.QCheckBox(self.gbAppearance)
        self.cbShow_2.setObjectName("cbShow_2")
        self.gridLayout_5.addWidget(self.cbShow_2, 0, 0, 1, 1)
        self.btnSetColor_2 = QtWidgets.QPushButton(self.gbAppearance)
        self.btnSetColor_2.setObjectName("btnSetColor_2")
        self.gridLayout_5.addWidget(self.btnSetColor_2, 0, 1, 1, 1)
        self.cbCoordinate = QtWidgets.QCheckBox(self.gbAppearance)
        self.cbCoordinate.setObjectName("cbCoordinate")
        self.gridLayout_5.addWidget(self.cbCoordinate, 2, 0, 1, 1)
        self.cbYgrid = QtWidgets.QCheckBox(self.gbAppearance)
        self.cbYgrid.setObjectName("cbYgrid")
        self.gridLayout_5.addWidget(self.cbYgrid, 1, 1, 1, 1)
        self.cbScale = QtWidgets.QCheckBox(self.gbAppearance)
        self.cbScale.setObjectName("cbScale")
        self.gridLayout_5.addWidget(self.cbScale, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbAppearance)
        self.gbLegend = QtWidgets.QGroupBox(self.page_2)
        self.gbLegend.setCheckable(True)
        self.gbLegend.setObjectName("gbLegend")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gbLegend)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cbDraggable = QtWidgets.QCheckBox(self.gbLegend)
        self.cbDraggable.setObjectName("cbDraggable")
        self.gridLayout_6.addWidget(self.cbDraggable, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gbLegend)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.btnReset = QtWidgets.QPushButton(self.gbLegend)
        self.btnReset.setObjectName("btnReset")
        self.gridLayout_6.addWidget(self.btnReset, 1, 1, 1, 1)
        self.cbLegendPosition = QtWidgets.QComboBox(self.gbLegend)
        self.cbLegendPosition.setObjectName("cbLegendPosition")
        self.gridLayout_6.addWidget(self.cbLegendPosition, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbLegend)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/f17.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon1, "")
        self.pageSeries = QtWidgets.QWidget()
        self.pageSeries.setGeometry(QtCore.QRect(0, 0, 378, 569))
        self.pageSeries.setObjectName("pageSeries")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageSeries)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.pageSeries)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.cbCurrentLine = QtWidgets.QComboBox(self.groupBox_6)
        self.cbCurrentLine.setObjectName("cbCurrentLine")
        self.horizontalLayout.addWidget(self.cbCurrentLine)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.pageSeries)
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 1, 0, 1, 1)
        self.cbLineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.cbLineWidth.setObjectName("cbLineWidth")
        self.gridLayout_7.addWidget(self.cbLineWidth, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.btnLineColor = QtWidgets.QPushButton(self.groupBox_5)
        self.btnLineColor.setObjectName("btnLineColor")
        self.gridLayout_7.addWidget(self.btnLineColor, 2, 2, 1, 1)
        self.cbDrawStyle = QtWidgets.QComboBox(self.groupBox_5)
        self.cbDrawStyle.setObjectName("cbDrawStyle")
        self.gridLayout_7.addWidget(self.cbDrawStyle, 1, 1, 1, 2)
        self.cbLineStyle = QtWidgets.QComboBox(self.groupBox_5)
        self.cbLineStyle.setObjectName("cbLineStyle")
        self.gridLayout_7.addWidget(self.cbLineStyle, 0, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.pageSeries)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 0, 1, 1)
        self.sbMarkerSize = QtWidgets.QSpinBox(self.groupBox)
        self.sbMarkerSize.setObjectName("sbMarkerSize")
        self.gridLayout_8.addWidget(self.sbMarkerSize, 1, 1, 1, 1)
        self.sbBorderlineWidth = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sbBorderlineWidth.setObjectName("sbBorderlineWidth")
        self.gridLayout_8.addWidget(self.sbBorderlineWidth, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 0, 0, 1, 1)
        self.btnMarkerColor = QtWidgets.QPushButton(self.groupBox)
        self.btnMarkerColor.setObjectName("btnMarkerColor")
        self.gridLayout_8.addWidget(self.btnMarkerColor, 1, 2, 1, 1)
        self.btnBorderlineColor = QtWidgets.QPushButton(self.groupBox)
        self.btnBorderlineColor.setObjectName("btnBorderlineColor")
        self.gridLayout_8.addWidget(self.btnBorderlineColor, 2, 2, 1, 1)
        self.cbMarkerStyle = QtWidgets.QComboBox(self.groupBox)
        self.cbMarkerStyle.setObjectName("cbMarkerStyle")
        self.gridLayout_8.addWidget(self.cbMarkerStyle, 0, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/dis3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.pageSeries, icon2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 378, 569))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cbShowXAxis = QtWidgets.QCheckBox(self.page_4)
        self.cbShowXAxis.setObjectName("cbShowXAxis")
        self.verticalLayout_5.addWidget(self.cbShowXAxis)
        self.line = QtWidgets.QFrame(self.page_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cbCoordinate_2 = QtWidgets.QComboBox(self.groupBox_8)
        self.cbCoordinate_2.setObjectName("cbCoordinate_2")
        self.gridLayout_9.addWidget(self.cbCoordinate_2, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 2, 0, 1, 1)
        self.dsbXmax = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.dsbXmax.setObjectName("dsbXmax")
        self.gridLayout_9.addWidget(self.dsbXmax, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 3, 0, 1, 1)
        self.dsbXmin = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.dsbXmin.setObjectName("dsbXmin")
        self.gridLayout_9.addWidget(self.dsbXmin, 0, 1, 1, 1)
        self.btnSetRange = QtWidgets.QPushButton(self.groupBox_8)
        self.btnSetRange.setObjectName("btnSetRange")
        self.gridLayout_9.addWidget(self.btnSetRange, 2, 2, 1, 1)
        self.cbReverse = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbReverse.setObjectName("cbReverse")
        self.gridLayout_9.addWidget(self.cbReverse, 3, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_7.setCheckable(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_10.addWidget(self.pushButton_16, 1, 0, 1, 1)
        self.cbXBold = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbXBold.setObjectName("cbXBold")
        self.gridLayout_10.addWidget(self.cbXBold, 1, 3, 1, 1)
        self.sbFontSize = QtWidgets.QSpinBox(self.groupBox_7)
        self.sbFontSize.setObjectName("sbFontSize")
        self.gridLayout_10.addWidget(self.sbFontSize, 1, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_10.addWidget(self.pushButton_15, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 1, 1, 1, 1)
        self.cbXItalic = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbXItalic.setObjectName("cbXItalic")
        self.gridLayout_10.addWidget(self.cbXItalic, 1, 4, 1, 1)
        self.lineEditXTitle = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEditXTitle.setObjectName("lineEditXTitle")
        self.gridLayout_10.addWidget(self.lineEditXTitle, 0, 1, 1, 4)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_9.setCheckable(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btnLabelStyle = QtWidgets.QPushButton(self.groupBox_9)
        self.btnLabelStyle.setObjectName("btnLabelStyle")
        self.gridLayout_11.addWidget(self.btnLabelStyle, 0, 0, 1, 1)
        self.lineEditLabelStyle = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditLabelStyle.setObjectName("lineEditLabelStyle")
        self.gridLayout_11.addWidget(self.lineEditLabelStyle, 0, 1, 1, 4)
        self.btnLabelFontColor = QtWidgets.QPushButton(self.groupBox_9)
        self.btnLabelFontColor.setObjectName("btnLabelFontColor")
        self.gridLayout_11.addWidget(self.btnLabelFontColor, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 1, 1, 1)
        self.sbLabelFontSize = QtWidgets.QSpinBox(self.groupBox_9)
        self.sbLabelFontSize.setObjectName("sbLabelFontSize")
        self.gridLayout_11.addWidget(self.sbLabelFontSize, 1, 2, 1, 1)
        self.cbLower = QtWidgets.QCheckBox(self.groupBox_9)
        self.cbLower.setObjectName("cbLower")
        self.gridLayout_11.addWidget(self.cbLower, 1, 3, 1, 1)
        self.cbUpper = QtWidgets.QCheckBox(self.groupBox_9)
        self.cbUpper.setObjectName("cbUpper")
        self.gridLayout_11.addWidget(self.cbUpper, 1, 4, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.btnLineColor_3 = QtWidgets.QPushButton(self.groupBox_10)
        self.btnLineColor_3.setObjectName("btnLineColor_3")
        self.gridLayout_12.addWidget(self.btnLineColor_3, 2, 2, 1, 1)
        self.cbShowMainGrid = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbShowMainGrid.setObjectName("cbShowMainGrid")
        self.gridLayout_12.addWidget(self.cbShowMainGrid, 2, 0, 1, 1)
        self.cbBottomLine = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbBottomLine.setObjectName("cbBottomLine")
        self.gridLayout_12.addWidget(self.cbBottomLine, 0, 0, 1, 1)
        self.btnLineColor_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.btnLineColor_2.setObjectName("btnLineColor_2")
        self.gridLayout_12.addWidget(self.btnLineColor_2, 0, 2, 1, 1)
        self.cbTopLine = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbTopLine.setObjectName("cbTopLine")
        self.gridLayout_12.addWidget(self.cbTopLine, 0, 1, 1, 1)
        self.cbLineStyle_2 = QtWidgets.QComboBox(self.groupBox_10)
        self.cbLineStyle_2.setObjectName("cbLineStyle_2")
        self.gridLayout_12.addWidget(self.cbLineStyle_2, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.cbBottomLine_3 = QtWidgets.QCheckBox(self.groupBox_11)
        self.cbBottomLine_3.setObjectName("cbBottomLine_3")
        self.gridLayout_13.addWidget(self.cbBottomLine_3, 0, 0, 1, 1)
        self.cbTopLine_3 = QtWidgets.QCheckBox(self.groupBox_11)
        self.cbTopLine_3.setObjectName("cbTopLine_3")
        self.gridLayout_13.addWidget(self.cbTopLine_3, 0, 1, 1, 1)
        self.btnLineColor_6 = QtWidgets.QPushButton(self.groupBox_11)
        self.btnLineColor_6.setObjectName("btnLineColor_6")
        self.gridLayout_13.addWidget(self.btnLineColor_6, 0, 2, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_13.addWidget(self.checkBox_23, 1, 0, 1, 1)
        self.cbLineStyle_4 = QtWidgets.QComboBox(self.groupBox_11)
        self.cbLineStyle_4.setObjectName("cbLineStyle_4")
        self.gridLayout_13.addWidget(self.cbLineStyle_4, 1, 1, 1, 1)
        self.btnLineColor_7 = QtWidgets.QPushButton(self.groupBox_11)
        self.btnLineColor_7.setObjectName("btnLineColor_7")
        self.gridLayout_13.addWidget(self.btnLineColor_7, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_11)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/602.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_4, icon3, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 378, 569))
        self.page_5.setObjectName("page_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbShowYAxis = QtWidgets.QCheckBox(self.page_5)
        self.cbShowYAxis.setObjectName("cbShowYAxis")
        self.verticalLayout_4.addWidget(self.cbShowYAxis)
        self.groupBox_16 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_18.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.cbCoordinate_3 = QtWidgets.QComboBox(self.groupBox_16)
        self.cbCoordinate_3.setObjectName("cbCoordinate_3")
        self.gridLayout_18.addWidget(self.cbCoordinate_3, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_16)
        self.label_25.setObjectName("label_25")
        self.gridLayout_18.addWidget(self.label_25, 2, 0, 1, 1)
        self.dsbYmax = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.dsbYmax.setObjectName("dsbYmax")
        self.gridLayout_18.addWidget(self.dsbYmax, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_16)
        self.label_26.setObjectName("label_26")
        self.gridLayout_18.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_16)
        self.label_27.setObjectName("label_27")
        self.gridLayout_18.addWidget(self.label_27, 3, 0, 1, 1)
        self.dsbYmin = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.dsbYmin.setObjectName("dsbYmin")
        self.gridLayout_18.addWidget(self.dsbYmin, 0, 1, 1, 1)
        self.btnSetRange_2 = QtWidgets.QPushButton(self.groupBox_16)
        self.btnSetRange_2.setObjectName("btnSetRange_2")
        self.gridLayout_18.addWidget(self.btnSetRange_2, 2, 2, 1, 1)
        self.cbReverse_2 = QtWidgets.QCheckBox(self.groupBox_16)
        self.cbReverse_2.setObjectName("cbReverse_2")
        self.gridLayout_18.addWidget(self.cbReverse_2, 3, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_16)
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_12.setCheckable(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_14.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.cbXBold_2 = QtWidgets.QCheckBox(self.groupBox_12)
        self.cbXBold_2.setObjectName("cbXBold_2")
        self.gridLayout_14.addWidget(self.cbXBold_2, 1, 3, 1, 1)
        self.sbFontSize_2 = QtWidgets.QSpinBox(self.groupBox_12)
        self.sbFontSize_2.setObjectName("sbFontSize_2")
        self.gridLayout_14.addWidget(self.sbFontSize_2, 1, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_14.addWidget(self.pushButton_18, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 1, 1, 1, 1)
        self.cbXItalic_2 = QtWidgets.QCheckBox(self.groupBox_12)
        self.cbXItalic_2.setObjectName("cbXItalic_2")
        self.gridLayout_14.addWidget(self.cbXItalic_2, 1, 4, 1, 1)
        self.lineEditXTitle_2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEditXTitle_2.setObjectName("lineEditXTitle_2")
        self.gridLayout_14.addWidget(self.lineEditXTitle_2, 0, 1, 1, 4)
        self.verticalLayout_4.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_13.setCheckable(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.btnLabelStyle_2 = QtWidgets.QPushButton(self.groupBox_13)
        self.btnLabelStyle_2.setObjectName("btnLabelStyle_2")
        self.gridLayout_15.addWidget(self.btnLabelStyle_2, 0, 0, 1, 1)
        self.lineEditLabelStyle_2 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEditLabelStyle_2.setObjectName("lineEditLabelStyle_2")
        self.gridLayout_15.addWidget(self.lineEditLabelStyle_2, 0, 1, 1, 4)
        self.btnLabelFontColor_2 = QtWidgets.QPushButton(self.groupBox_13)
        self.btnLabelFontColor_2.setObjectName("btnLabelFontColor_2")
        self.gridLayout_15.addWidget(self.btnLabelFontColor_2, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_13)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 1, 1, 1, 1)
        self.sbLabelFontSize_2 = QtWidgets.QSpinBox(self.groupBox_13)
        self.sbLabelFontSize_2.setObjectName("sbLabelFontSize_2")
        self.gridLayout_15.addWidget(self.sbLabelFontSize_2, 1, 2, 1, 1)
        self.cbLower_2 = QtWidgets.QCheckBox(self.groupBox_13)
        self.cbLower_2.setObjectName("cbLower_2")
        self.gridLayout_15.addWidget(self.cbLower_2, 1, 3, 1, 1)
        self.cbUpper_2 = QtWidgets.QCheckBox(self.groupBox_13)
        self.cbUpper_2.setObjectName("cbUpper_2")
        self.gridLayout_15.addWidget(self.cbUpper_2, 1, 4, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.btnLineColor_4 = QtWidgets.QPushButton(self.groupBox_14)
        self.btnLineColor_4.setObjectName("btnLineColor_4")
        self.gridLayout_16.addWidget(self.btnLineColor_4, 2, 2, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_16.addWidget(self.checkBox_21, 2, 0, 1, 1)
        self.cbBottomLine_2 = QtWidgets.QCheckBox(self.groupBox_14)
        self.cbBottomLine_2.setObjectName("cbBottomLine_2")
        self.gridLayout_16.addWidget(self.cbBottomLine_2, 0, 0, 1, 1)
        self.btnLineColor_5 = QtWidgets.QPushButton(self.groupBox_14)
        self.btnLineColor_5.setObjectName("btnLineColor_5")
        self.gridLayout_16.addWidget(self.btnLineColor_5, 0, 2, 1, 1)
        self.cbTopLine_2 = QtWidgets.QCheckBox(self.groupBox_14)
        self.cbTopLine_2.setObjectName("cbTopLine_2")
        self.gridLayout_16.addWidget(self.cbTopLine_2, 0, 1, 1, 1)
        self.cbLineStyle_3 = QtWidgets.QComboBox(self.groupBox_14)
        self.cbLineStyle_3.setObjectName("cbLineStyle_3")
        self.gridLayout_16.addWidget(self.cbLineStyle_3, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_17.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.cbBottomLine_4 = QtWidgets.QCheckBox(self.groupBox_15)
        self.cbBottomLine_4.setObjectName("cbBottomLine_4")
        self.gridLayout_17.addWidget(self.cbBottomLine_4, 0, 0, 1, 1)
        self.cbTopLine_4 = QtWidgets.QCheckBox(self.groupBox_15)
        self.cbTopLine_4.setObjectName("cbTopLine_4")
        self.gridLayout_17.addWidget(self.cbTopLine_4, 0, 1, 1, 1)
        self.btnLineColor_8 = QtWidgets.QPushButton(self.groupBox_15)
        self.btnLineColor_8.setObjectName("btnLineColor_8")
        self.gridLayout_17.addWidget(self.btnLineColor_8, 0, 2, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_17.addWidget(self.checkBox_24, 1, 0, 1, 1)
        self.cbLineStyle_5 = QtWidgets.QComboBox(self.groupBox_15)
        self.cbLineStyle_5.setObjectName("cbLineStyle_5")
        self.gridLayout_17.addWidget(self.cbLineStyle_5, 1, 1, 1, 1)
        self.btnLineColor_9 = QtWidgets.QPushButton(self.groupBox_15)
        self.btnLineColor_9.setObjectName("btnLineColor_9")
        self.gridLayout_17.addWidget(self.btnLineColor_9, 1, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_15)
        self.toolBox.addItem(self.page_5, icon3, "")
        self.horizontalLayout_3.addWidget(self.toolBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        plt_gui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(plt_gui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 772, 17))
        self.menuBar.setObjectName("menuBar")
        plt_gui.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(plt_gui)
        self.statusBar.setObjectName("statusBar")
        plt_gui.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(plt_gui)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(plt_gui)
        self.toolBox.setCurrentIndex(1)
        self.actionExit.triggered.connect(plt_gui.close)
        QtCore.QMetaObject.connectSlotsByName(plt_gui)

    def retranslateUi(self, plt_gui):
        _translate = QtCore.QCoreApplication.translate
        plt_gui.setWindowTitle(_translate("plt_gui", "plt_gui"))
        self.gbSuptitle.setTitle(_translate("plt_gui", "1.1 suptitle"))
        self.btnTitle.setText(_translate("plt_gui", "set title"))
        self.cbBold.setText(_translate("plt_gui", "Bold"))
        self.label.setText(_translate("plt_gui", "font size"))
        self.cbItalic.setText(_translate("plt_gui", "Italic"))
        self.btnFontColor.setText(_translate("plt_gui", "font color"))
        self.btnBackgroundColor.setText(_translate("plt_gui", "background color"))
        self.gbBackground.setTitle(_translate("plt_gui", "1.2 background"))
        self.cbShow.setText(_translate("plt_gui", "show background and borderline"))
        self.btnSetColor.setText(_translate("plt_gui", "set background color"))
        self.label_2.setText(_translate("plt_gui", "figure style"))
        self.gbInterval.setTitle(_translate("plt_gui", "1.3 interval"))
        self.label_8.setText(_translate("plt_gui", "hspace"))
        self.label_4.setText(_translate("plt_gui", "bottom"))
        self.label_7.setText(_translate("plt_gui", "top"))
        self.label_3.setText(_translate("plt_gui", "left"))
        self.label_5.setText(_translate("plt_gui", "wspace"))
        self.label_6.setText(_translate("plt_gui", "right"))
        self.btnTightLayout.setText(_translate("plt_gui", "tight layout"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("plt_gui", "Figure operation"))
        self.cbVisible.setText(_translate("plt_gui", "plot visible "))
        self.gbTitle.setTitle(_translate("plt_gui", "subplot title"))
        self.cbItalic_2.setText(_translate("plt_gui", "Italic"))
        self.label_9.setText(_translate("plt_gui", "font size"))
        self.btnSetTitle.setText(_translate("plt_gui", "set title"))
        self.cbBold_2.setText(_translate("plt_gui", "Bold"))
        self.btnBackgroundColor_2.setText(_translate("plt_gui", "background color"))
        self.btnFontColor_2.setText(_translate("plt_gui", "font color"))
        self.gbAppearance.setTitle(_translate("plt_gui", "subplot appearance"))
        self.cbXgrid.setText(_translate("plt_gui", "x grid"))
        self.cbShow_2.setText(_translate("plt_gui", "show background and borderline"))
        self.btnSetColor_2.setText(_translate("plt_gui", "set background color"))
        self.cbCoordinate.setText(_translate("plt_gui", "coordinate"))
        self.cbYgrid.setText(_translate("plt_gui", "y grid"))
        self.cbScale.setText(_translate("plt_gui", "scale degree"))
        self.gbLegend.setTitle(_translate("plt_gui", "legend"))
        self.cbDraggable.setText(_translate("plt_gui", "draggable"))
        self.label_10.setText(_translate("plt_gui", "legend position"))
        self.btnReset.setText(_translate("plt_gui", "reset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("plt_gui", "Axes operation"))
        self.label_11.setText(_translate("plt_gui", "current line"))
        self.groupBox_5.setTitle(_translate("plt_gui", "line appearance"))
        self.label_13.setText(_translate("plt_gui", "draw style"))
        self.label_14.setText(_translate("plt_gui", "line width"))
        self.label_12.setText(_translate("plt_gui", "line style"))
        self.btnLineColor.setText(_translate("plt_gui", "line color"))
        self.groupBox.setTitle(_translate("plt_gui", "marker"))
        self.label_17.setText(_translate("plt_gui", "borderline width"))
        self.label_16.setText(_translate("plt_gui", "marker size"))
        self.label_15.setText(_translate("plt_gui", "marker style"))
        self.btnMarkerColor.setText(_translate("plt_gui", "marker color"))
        self.btnBorderlineColor.setText(_translate("plt_gui", "borderline color"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageSeries), _translate("plt_gui", "line edit"))
        self.cbShowXAxis.setText(_translate("plt_gui", "show x axis"))
        self.groupBox_8.setTitle(_translate("plt_gui", "value characteristic"))
        self.label_19.setText(_translate("plt_gui", "max"))
        self.label_18.setText(_translate("plt_gui", "min"))
        self.label_20.setText(_translate("plt_gui", "coordinate"))
        self.btnSetRange.setText(_translate("plt_gui", "set range"))
        self.cbReverse.setText(_translate("plt_gui", "reverse"))
        self.groupBox_7.setTitle(_translate("plt_gui", "x title"))
        self.pushButton_16.setText(_translate("plt_gui", "text color"))
        self.cbXBold.setText(_translate("plt_gui", "Bold"))
        self.pushButton_15.setText(_translate("plt_gui", "set title"))
        self.label_21.setText(_translate("plt_gui", "font size"))
        self.cbXItalic.setText(_translate("plt_gui", "Italic"))
        self.groupBox_9.setTitle(_translate("plt_gui", "coordinate label"))
        self.btnLabelStyle.setText(_translate("plt_gui", "set label style"))
        self.btnLabelFontColor.setText(_translate("plt_gui", "set label color"))
        self.label_22.setText(_translate("plt_gui", "font size"))
        self.cbLower.setText(_translate("plt_gui", "lower"))
        self.cbUpper.setText(_translate("plt_gui", "upper"))
        self.groupBox_10.setTitle(_translate("plt_gui", "coordinate"))
        self.btnLineColor_3.setText(_translate("plt_gui", "line color"))
        self.cbShowMainGrid.setText(_translate("plt_gui", "show main grid"))
        self.cbBottomLine.setText(_translate("plt_gui", "bottom line"))
        self.btnLineColor_2.setText(_translate("plt_gui", "line color"))
        self.cbTopLine.setText(_translate("plt_gui", "top line"))
        self.groupBox_11.setTitle(_translate("plt_gui", "minor coordinate"))
        self.cbBottomLine_3.setText(_translate("plt_gui", "bottom line"))
        self.cbTopLine_3.setText(_translate("plt_gui", "top line"))
        self.btnLineColor_6.setText(_translate("plt_gui", "line color"))
        self.checkBox_23.setText(_translate("plt_gui", "show minor grid"))
        self.btnLineColor_7.setText(_translate("plt_gui", "line color"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("plt_gui", "x axis"))
        self.cbShowYAxis.setText(_translate("plt_gui", "show y axis"))
        self.groupBox_16.setTitle(_translate("plt_gui", "value characteristic"))
        self.label_25.setText(_translate("plt_gui", "max"))
        self.label_26.setText(_translate("plt_gui", "min"))
        self.label_27.setText(_translate("plt_gui", "coordinate"))
        self.btnSetRange_2.setText(_translate("plt_gui", "set range"))
        self.cbReverse_2.setText(_translate("plt_gui", "reverse"))
        self.groupBox_12.setTitle(_translate("plt_gui", "y title"))
        self.pushButton_17.setText(_translate("plt_gui", "text color"))
        self.cbXBold_2.setText(_translate("plt_gui", "Bold"))
        self.pushButton_18.setText(_translate("plt_gui", "set title"))
        self.label_23.setText(_translate("plt_gui", "font size"))
        self.cbXItalic_2.setText(_translate("plt_gui", "Italic"))
        self.groupBox_13.setTitle(_translate("plt_gui", "coordinate label"))
        self.btnLabelStyle_2.setText(_translate("plt_gui", "set label style"))
        self.btnLabelFontColor_2.setText(_translate("plt_gui", "set label color"))
        self.label_24.setText(_translate("plt_gui", "font size"))
        self.cbLower_2.setText(_translate("plt_gui", "lower"))
        self.cbUpper_2.setText(_translate("plt_gui", "upper"))
        self.groupBox_14.setTitle(_translate("plt_gui", "coordinate"))
        self.btnLineColor_4.setText(_translate("plt_gui", "line color"))
        self.checkBox_21.setText(_translate("plt_gui", "show main grid"))
        self.cbBottomLine_2.setText(_translate("plt_gui", "bottom line"))
        self.btnLineColor_5.setText(_translate("plt_gui", "line color"))
        self.cbTopLine_2.setText(_translate("plt_gui", "top line"))
        self.groupBox_15.setTitle(_translate("plt_gui", "minor coordinate"))
        self.cbBottomLine_4.setText(_translate("plt_gui", "bottom line"))
        self.cbTopLine_4.setText(_translate("plt_gui", "top line"))
        self.btnLineColor_8.setText(_translate("plt_gui", "line color"))
        self.checkBox_24.setText(_translate("plt_gui", "show minor grid"))
        self.btnLineColor_9.setText(_translate("plt_gui", "line color"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("plt_gui", "Y axis"))
        self.actionExit.setText(_translate("plt_gui", "Exit"))
import res_rc
