# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(379, 284)
        self.centralWidget = QtWidgets.QWidget(Widget)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 336, 160))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.slider = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.slider.setFont(font)
        self.slider.setObjectName("slider")
        self.gridLayout.addWidget(self.slider, 0, 0, 1, 1)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.verticalLayoutWidget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout.addWidget(self.horizontalScrollBar, 1, 1, 1, 1)
        self.scrollbar = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.scrollbar.setFont(font)
        self.scrollbar.setObjectName("scrollbar")
        self.gridLayout.addWidget(self.scrollbar, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 1)
        self.progressbar = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.progressbar.setFont(font)
        self.progressbar.setObjectName("progressbar")
        self.gridLayout.addWidget(self.progressbar, 2, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressbar_setting = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.progressbar_setting.setFont(font)
        self.progressbar_setting.setObjectName("progressbar_setting")
        self.gridLayout_2.addWidget(self.progressbar_setting, 0, 0, 1, 1)
        self.textvisible = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.textvisible.setObjectName("textvisible")
        self.gridLayout_2.addWidget(self.textvisible, 1, 0, 1, 1)
        self.inverted_appearance = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.inverted_appearance.setObjectName("inverted_appearance")
        self.gridLayout_2.addWidget(self.inverted_appearance, 3, 0, 1, 1)
        self.value = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.value.setObjectName("value")
        self.gridLayout_2.addWidget(self.value, 3, 1, 1, 1)
        self.percent = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.percent.setObjectName("percent")
        self.gridLayout_2.addWidget(self.percent, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        Widget.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Widget)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 379, 17))
        self.menuBar.setObjectName("menuBar")
        Widget.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Widget)
        self.mainToolBar.setObjectName("mainToolBar")
        Widget.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Widget)
        self.statusBar.setObjectName("statusBar")
        Widget.setStatusBar(self.statusBar)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.slider.setText(_translate("Widget", "Slider"))
        self.scrollbar.setText(_translate("Widget", "ScrollBar"))
        self.progressbar.setText(_translate("Widget", "ProgressBar"))
        self.progressbar_setting.setText(_translate("Widget", "ProgressBar setting"))
        self.textvisible.setText(_translate("Widget", "textvisible"))
        self.inverted_appearance.setText(_translate("Widget", "inverted appearance"))
        self.value.setText(_translate("Widget", "value"))
        self.percent.setText(_translate("Widget", "%"))
