# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphicsvideoitem.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphicsVideoItem(object):
    def setupUi(self, GraphicsVideoItem):
        GraphicsVideoItem.setObjectName("GraphicsVideoItem")
        GraphicsVideoItem.resize(514, 405)
        self.centralWidget = QtWidgets.QWidget(GraphicsVideoItem)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbtOpen = QtWidgets.QPushButton(self.widget_2)
        self.pbtOpen.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtOpen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtOpen.setIcon(icon)
        self.pbtOpen.setObjectName("pbtOpen")
        self.horizontalLayout.addWidget(self.pbtOpen)
        self.pbtPlay = QtWidgets.QPushButton(self.widget_2)
        self.pbtPlay.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtPlay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/620.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtPlay.setIcon(icon1)
        self.pbtPlay.setObjectName("pbtPlay")
        self.horizontalLayout.addWidget(self.pbtPlay)
        self.pbtPause = QtWidgets.QPushButton(self.widget_2)
        self.pbtPause.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtPause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtPause.setIcon(icon2)
        self.pbtPause.setObjectName("pbtPause")
        self.horizontalLayout.addWidget(self.pbtPause)
        self.pbtStop = QtWidgets.QPushButton(self.widget_2)
        self.pbtStop.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtStop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtStop.setIcon(icon3)
        self.pbtStop.setObjectName("pbtStop")
        self.horizontalLayout.addWidget(self.pbtStop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbtVolume = QtWidgets.QPushButton(self.widget_2)
        self.pbtVolume.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtVolume.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/volumn.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtVolume.setIcon(icon4)
        self.pbtVolume.setObjectName("pbtVolume")
        self.horizontalLayout.addWidget(self.pbtVolume)
        self.SliderVolume = QtWidgets.QSlider(self.widget_2)
        self.SliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.SliderVolume.setObjectName("SliderVolume")
        self.horizontalLayout.addWidget(self.SliderVolume)
        self.pbtText = QtWidgets.QPushButton(self.widget_2)
        self.pbtText.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtText.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/165.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtText.setIcon(icon5)
        self.pbtText.setObjectName("pbtText")
        self.horizontalLayout.addWidget(self.pbtText)
        self.pbtPause_3 = QtWidgets.QPushButton(self.widget_2)
        self.pbtPause_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtPause_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtPause_3.setIcon(icon6)
        self.pbtPause_3.setObjectName("pbtPause_3")
        self.horizontalLayout.addWidget(self.pbtPause_3)
        self.pbtPause_4 = QtWidgets.QPushButton(self.widget_2)
        self.pbtPause_4.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtPause_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtPause_4.setIcon(icon7)
        self.pbtPause_4.setObjectName("pbtPause_4")
        self.horizontalLayout.addWidget(self.pbtPause_4)
        self.pbtExit = QtWidgets.QPushButton(self.widget_2)
        self.pbtExit.setMinimumSize(QtCore.QSize(30, 30))
        self.pbtExit.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtExit.setIcon(icon8)
        self.pbtExit.setObjectName("pbtExit")
        self.horizontalLayout.addWidget(self.pbtExit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayout.setStretch(5, 2)
        self.horizontalLayout.setStretch(6, 1)
        self.horizontalLayout.setStretch(7, 3)
        self.horizontalLayout.setStretch(11, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.labelFile = QtWidgets.QLabel(self.widget_3)
        self.labelFile.setText("")
        self.labelFile.setObjectName("labelFile")
        self.gridLayout.addWidget(self.labelFile, 0, 0, 1, 1)
        self.labelTime = QtWidgets.QLabel(self.widget_3)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout.addWidget(self.labelTime, 1, 2, 1, 1)
        self.SliderProgress = QtWidgets.QSlider(self.widget_3)
        self.SliderProgress.setOrientation(QtCore.Qt.Horizontal)
        self.SliderProgress.setObjectName("SliderProgress")
        self.gridLayout.addWidget(self.SliderProgress, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        GraphicsVideoItem.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(GraphicsVideoItem)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 514, 17))
        self.menuBar.setObjectName("menuBar")
        GraphicsVideoItem.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(GraphicsVideoItem)
        self.mainToolBar.setObjectName("mainToolBar")
        GraphicsVideoItem.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(GraphicsVideoItem)
        self.statusBar.setObjectName("statusBar")
        GraphicsVideoItem.setStatusBar(self.statusBar)

        self.retranslateUi(GraphicsVideoItem)
        self.pbtExit.clicked.connect(GraphicsVideoItem.close)
        QtCore.QMetaObject.connectSlotsByName(GraphicsVideoItem)

    def retranslateUi(self, GraphicsVideoItem):
        _translate = QtCore.QCoreApplication.translate
        GraphicsVideoItem.setWindowTitle(_translate("GraphicsVideoItem", "GraphicsVideoItem"))
        self.labelTime.setText(_translate("GraphicsVideoItem", "0:00"))
import res_rc
