# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multimedia.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_multimedia(object):
    def setupUi(self, multimedia):
        multimedia.setObjectName("multimedia")
        multimedia.resize(812, 612)
        multimedia.setMinimumSize(QtCore.QSize(800, 600))
        multimedia.setMaximumSize(QtCore.QSize(812, 612))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(multimedia)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(multimedia)
        self.groupBox.setMinimumSize(QtCore.QSize(800, 600))
        self.groupBox.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnDelete = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/318.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon1)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.btnClear = QtWidgets.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/212.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon2)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_2.addWidget(self.btnClear)
        self.verticalLayout.addWidget(self.widget)
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnPlay = QtWidgets.QPushButton(self.widget_2)
        self.btnPlay.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/620.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon3)
        self.btnPlay.setObjectName("btnPlay")
        self.horizontalLayout_3.addWidget(self.btnPlay)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnPause = QtWidgets.QPushButton(self.widget_2)
        self.btnPause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPause.setIcon(icon4)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout_3.addWidget(self.btnPause)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnStop = QtWidgets.QPushButton(self.widget_2)
        self.btnStop.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon5)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnBack = QtWidgets.QPushButton(self.widget_2)
        self.btnBack.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/616.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon6)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout_3.addWidget(self.btnBack)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnNext = QtWidgets.QPushButton(self.widget_2)
        self.btnNext.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/630.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon7)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_3.addWidget(self.btnNext)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnVolume = QtWidgets.QPushButton(self.widget_2)
        self.btnVolume.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/volumn.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVolume.setIcon(icon8)
        self.btnVolume.setObjectName("btnVolume")
        self.horizontalLayout_3.addWidget(self.btnVolume)
        self.SliderVolume = QtWidgets.QSlider(self.widget_2)
        self.SliderVolume.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SliderVolume.setMaximum(100)
        self.SliderVolume.setSingleStep(1)
        self.SliderVolume.setPageStep(10)
        self.SliderVolume.setProperty("value", 50)
        self.SliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.SliderVolume.setInvertedAppearance(False)
        self.SliderVolume.setInvertedControls(False)
        self.SliderVolume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SliderVolume.setTickInterval(10)
        self.SliderVolume.setObjectName("SliderVolume")
        self.horizontalLayout_3.addWidget(self.SliderVolume)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelName = QtWidgets.QLabel(self.widget_3)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_4.addWidget(self.labelName)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.SliderSong = QtWidgets.QSlider(self.widget_3)
        self.SliderSong.setOrientation(QtCore.Qt.Horizontal)
        self.SliderSong.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.SliderSong.setObjectName("SliderSong")
        self.horizontalLayout_4.addWidget(self.SliderSong)
        self.labelTime = QtWidgets.QLabel(self.widget_3)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_4.addWidget(self.labelTime)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 7)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(multimedia)
        QtCore.QMetaObject.connectSlotsByName(multimedia)

    def retranslateUi(self, multimedia):
        _translate = QtCore.QCoreApplication.translate
        multimedia.setWindowTitle(_translate("multimedia", "multimedia"))
        self.groupBox.setTitle(_translate("multimedia", "Play Music"))
        self.btnAdd.setText(_translate("multimedia", "add"))
        self.btnDelete.setText(_translate("multimedia", "delete"))
        self.btnClear.setText(_translate("multimedia", "clear"))
        self.labelName.setText(_translate("multimedia", "None"))
        self.labelTime.setText(_translate("multimedia", "time"))
import res_rc
