# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audioinput.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioInput(object):
    def setupUi(self, AudioInput):
        AudioInput.setObjectName("AudioInput")
        AudioInput.resize(505, 530)
        self.centralWidget = QtWidgets.QWidget(AudioInput)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtDevice = QtWidgets.QRadioButton(self.groupBox)
        self.rbtDevice.setObjectName("rbtDevice")
        self.horizontalLayout.addWidget(self.rbtDevice)
        self.rbtQFile = QtWidgets.QRadioButton(self.groupBox)
        self.rbtQFile.setObjectName("rbtQFile")
        self.horizontalLayout.addWidget(self.rbtQFile)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxDevice = QtWidgets.QGroupBox(self.frame)
        self.groupBoxDevice.setObjectName("groupBoxDevice")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxDevice)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(self.groupBoxDevice)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBoxDevice)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 10, 0, 1, 2)
        self.cbSampleType = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbSampleType.setMinimumSize(QtCore.QSize(0, 40))
        self.cbSampleType.setObjectName("cbSampleType")
        self.gridLayout.addWidget(self.cbSampleType, 5, 1, 1, 1)
        self.cbFrequency = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbFrequency.setMinimumSize(QtCore.QSize(0, 40))
        self.cbFrequency.setObjectName("cbFrequency")
        self.gridLayout.addWidget(self.cbFrequency, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.labelVolume = QtWidgets.QLabel(self.groupBoxDevice)
        self.labelVolume.setObjectName("labelVolume")
        self.gridLayout.addWidget(self.labelVolume, 11, 0, 1, 1)
        self.cbEndianess = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbEndianess.setMinimumSize(QtCore.QSize(0, 40))
        self.cbEndianess.setObjectName("cbEndianess")
        self.gridLayout.addWidget(self.cbEndianess, 7, 1, 1, 1)
        self.cbChannels = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbChannels.setMinimumSize(QtCore.QSize(0, 40))
        self.cbChannels.setObjectName("cbChannels")
        self.gridLayout.addWidget(self.cbChannels, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.cbEquip = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbEquip.setMinimumSize(QtCore.QSize(0, 40))
        self.cbEquip.setObjectName("cbEquip")
        self.gridLayout.addWidget(self.cbEquip, 0, 1, 1, 1)
        self.cbCodec = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbCodec.setMinimumSize(QtCore.QSize(0, 40))
        self.cbCodec.setObjectName("cbCodec")
        self.gridLayout.addWidget(self.cbCodec, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 2)
        self.SliderVolume = QtWidgets.QSlider(self.groupBoxDevice)
        self.SliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.SliderVolume.setObjectName("SliderVolume")
        self.gridLayout.addWidget(self.SliderVolume, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxDevice)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBoxDevice)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.cbSampleSize = QtWidgets.QComboBox(self.groupBoxDevice)
        self.cbSampleSize.setMinimumSize(QtCore.QSize(0, 40))
        self.cbSampleSize.setObjectName("cbSampleSize")
        self.gridLayout.addWidget(self.cbSampleSize, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxDevice)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxDevice)
        self.groupBoxBuffer = QtWidgets.QGroupBox(self.frame)
        self.groupBoxBuffer.setObjectName("groupBoxBuffer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxBuffer)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelIODevice = QtWidgets.QLabel(self.groupBoxBuffer)
        self.labelIODevice.setObjectName("labelIODevice")
        self.gridLayout_3.addWidget(self.labelIODevice, 9, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBoxBuffer)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbMin = QtWidgets.QProgressBar(self.widget)
        self.pbMin.setMinimumSize(QtCore.QSize(40, 0))
        self.pbMin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbMin.setAutoFillBackground(False)
        self.pbMin.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pbMin.setProperty("value", 50)
        self.pbMin.setTextVisible(False)
        self.pbMin.setOrientation(QtCore.Qt.Vertical)
        self.pbMin.setInvertedAppearance(False)
        self.pbMin.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pbMin.setObjectName("pbMin")
        self.gridLayout_2.addWidget(self.pbMin, 0, 1, 1, 1)
        self.pbMax = QtWidgets.QProgressBar(self.widget)
        self.pbMax.setMinimumSize(QtCore.QSize(40, 0))
        self.pbMax.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbMax.setAutoFillBackground(False)
        self.pbMax.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pbMax.setProperty("value", 50)
        self.pbMax.setTextVisible(False)
        self.pbMax.setOrientation(QtCore.Qt.Vertical)
        self.pbMax.setInvertedAppearance(False)
        self.pbMax.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pbMax.setObjectName("pbMax")
        self.gridLayout_2.addWidget(self.pbMax, 0, 0, 1, 1)
        self.pbDifference = QtWidgets.QProgressBar(self.widget)
        self.pbDifference.setMinimumSize(QtCore.QSize(40, 0))
        self.pbDifference.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pbDifference.setAutoFillBackground(False)
        self.pbDifference.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pbDifference.setProperty("value", 50)
        self.pbDifference.setTextVisible(False)
        self.pbDifference.setOrientation(QtCore.Qt.Vertical)
        self.pbDifference.setInvertedAppearance(False)
        self.pbDifference.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pbDifference.setObjectName("pbDifference")
        self.gridLayout_2.addWidget(self.pbDifference, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBoxBuffer)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 3, 0, 1, 1)
        self.labelBufferSize = QtWidgets.QLabel(self.groupBoxBuffer)
        self.labelBufferSize.setObjectName("labelBufferSize")
        self.gridLayout_3.addWidget(self.labelBufferSize, 7, 0, 1, 1)
        self.labelBytesReady = QtWidgets.QLabel(self.groupBoxBuffer)
        self.labelBytesReady.setObjectName("labelBytesReady")
        self.gridLayout_3.addWidget(self.labelBytesReady, 8, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxBuffer)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        AudioInput.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(AudioInput)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 505, 17))
        self.menuBar.setObjectName("menuBar")
        AudioInput.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(AudioInput)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        AudioInput.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(AudioInput)
        self.statusBar.setObjectName("statusBar")
        AudioInput.setStatusBar(self.statusBar)
        self.actionRecord = QtWidgets.QAction(AudioInput)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon)
        self.actionRecord.setObjectName("actionRecord")
        self.actionPause = QtWidgets.QAction(AudioInput)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon1)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(AudioInput)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon2)
        self.actionStop.setObjectName("actionStop")
        self.actionExit = QtWidgets.QAction(AudioInput)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionStart = QtWidgets.QAction(AudioInput)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/626.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon4)
        self.actionStart.setObjectName("actionStart")
        self.mainToolBar.addAction(self.actionRecord)
        self.mainToolBar.addAction(self.actionStart)
        self.mainToolBar.addAction(self.actionPause)
        self.mainToolBar.addAction(self.actionStop)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(AudioInput)
        self.actionExit.triggered.connect(AudioInput.close)
        QtCore.QMetaObject.connectSlotsByName(AudioInput)

    def retranslateUi(self, AudioInput):
        _translate = QtCore.QCoreApplication.translate
        AudioInput.setWindowTitle(_translate("AudioInput", "AudioInput"))
        self.groupBox.setTitle(_translate("AudioInput", "Read Method"))
        self.rbtDevice.setText(_translate("AudioInput", "IO Device"))
        self.rbtQFile.setText(_translate("AudioInput", "QFile"))
        self.groupBoxDevice.setTitle(_translate("AudioInput", "support device"))
        self.label_2.setText(_translate("AudioInput", "Codec"))
        self.label_4.setText(_translate("AudioInput", "Channels"))
        self.label_7.setText(_translate("AudioInput", "Endianness"))
        self.label_5.setText(_translate("AudioInput", "SampleType"))
        self.labelVolume.setText(_translate("AudioInput", "volume(100%)"))
        self.label_6.setText(_translate("AudioInput", "SampleSize"))
        self.label_8.setText(_translate("AudioInput", "8000Hz 1 channel audio/pcm 8bits UnSignedInt LittleEndian"))
        self.label_3.setText(_translate("AudioInput", "Frequency(Hz)"))
        self.label.setText(_translate("AudioInput", "Input Equipment"))
        self.groupBoxBuffer.setTitle(_translate("AudioInput", "buffer info"))
        self.labelIODevice.setText(_translate("AudioInput", "IODevice:"))
        self.label_10.setText(_translate("AudioInput", "max"))
        self.label_11.setText(_translate("AudioInput", "min"))
        self.label_12.setText(_translate("AudioInput", "max-min"))
        self.labelBufferSize.setText(_translate("AudioInput", "bufferSize:"))
        self.labelBytesReady.setText(_translate("AudioInput", "bytesReady:"))
        self.actionRecord.setText(_translate("AudioInput", "Record"))
        self.actionPause.setText(_translate("AudioInput", "Pause"))
        self.actionStop.setText(_translate("AudioInput", "Stop"))
        self.actionExit.setText(_translate("AudioInput", "Exit"))
        self.actionStart.setText(_translate("AudioInput", "Start"))
import res_rc
